cypress/support/commands.ts
cypress/support/testdata.ts

Our E2E tests are failing consistently on master branch. I've run the tests locally with these changes and so far they haven't failed. 🤞🏽 
Run the E2E tests repeatedly
```
npm run tests-init
npm run tests-e2e
```

ci: Fix flaky E2E tests

---

cypress/support/commands.ts

Another attempt to reduce the flakiness of Cypress E2E test assertions

ci: Lighten the assertion to try to fix flaky tests

---

cypress/support/commands.ts

Eliminates the cy.url() assertion on the app name

ci: More test flakiness fixing

---

.github/workflows/cli_release.yaml
README.md

1. Adds additional permissions to the CLI release script so that it will work.
2. Cleanup the README

fix: CLI release script needs permissions, cleanup README

---

libs/apps/uesio/studio/bundle/views/appnav.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml

This reverts commit 3138c932754f9fcdc515bf444d50b56a878f924d.

Revert "fix(tests): Switch to route/REDIRECT for App and Workspace creation

---

apps/platform/go.mod
apps/platform/go.sum
apps/platform/pkg/auth/cognito/cognitoauth.go

This fixes the JWT security issue that is showing up in our security tab.
Everything should work the same as before.

Fix jwt security issue

---

apps/platform/pkg/cache/redis.go

Adds the REDIS_TLS environment variable.

Add redis use tls option

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/codepanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexpanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx

Fixes #3806 
Fixes the close buttons for the code panel and the index panel.
Try to close those panels!

Fix close buttons for code panel and index panel

---

libs/apps/uesio/studio/bundle/componentpacks/main/src/components/previewbutton/previewbutton.tsx

Fix route generator form

---

apps/platform/pkg/bot/systemdialect/systembot_after_workspace.go
apps/platform/pkg/bundlestore/platformbundlestore/platformbundlestore.go
apps/platform/pkg/deploy/deploy.go

Fix bundling tests

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dialogplain/dialogplain.tsx

Adds default dimensions to the dialog component.

Fix dialog default dimensions

---

apps/platform/pkg/bundlestore/platformbundlestore/platformbundlestore.go
apps/platform/pkg/bundlestore/systembundlestore/systembundlestore.go
apps/platform/pkg/datasource/metadata.go
apps/platform/pkg/routing/deps.go

Prevents you from getting access errors from routeassignments to routes you don't have access to.

Fix errors with route assignments

---

libs/apps/uesio/studio/bundle/components/emptystate.yaml
libs/apps/uesio/studio/bundle/views/app.yaml
libs/apps/uesio/studio/bundle/views/workspace.yaml

Adds a simple app home with links to sites and workspaces. In the future we can add a lot more detail here.

add simple app home

---

libs/apps/uesio/core/bundle/componentpacks/app/src/components/logingoogle/logingoogle.tsx
libs/apps/uesio/core/bundle/componentpacks/app/src/utilities/logingoogle/logingoogle.tsx

Allows you to optionally use the google one-tap flow for login.

Enable one-tap google login

---

apps/platform/pkg/bot/jsdialect/jsdialect.go

closes #3841 
Previously, in Site mode, we were only caching Bot programs using the Bot's key, which meant that, for 5-15 minutes after you updated a Site to a new bundle, the previous bot code would still be used.
Now, we use the context site's app name and bundle version in the Site-mode Bot program cache key, to ensure that net-new Bot code will be immediately used after the site is updated to a new Bundle version.
See testing steps in the issue description.

fix(bots): Bundled bot code not invalidated immediately after site bundle update

---

libs/apps/uesio/io/bundle/components/card.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/scrollpanel/card.yaml

Creates a new card component
If relevant, explain how to test the change locally

feat: new card component

---

libs/apps/uesio/studio/bundle/componentvariants/uesio/io/tile/appitem.yaml

Prevents the avatar of appitems from shrinnking

Fix appitem shrink

---

libs/apps/uesio/studio/bundle/fields/uesio/studio/usage_plan/limits.yaml

delete cascade limits on plan deletion
Delete a plan a verify that the limits are also deleted

feat: delete cascade limits on plan deletion

---

libs/apps/uesio/studio/bundle/permissionsets/admin.yaml
libs/apps/uesio/studio/bundle/routes/manageplan.yaml
libs/apps/uesio/studio/bundle/routes/manageplans.yaml
libs/apps/uesio/studio/bundle/views/adminnav.yaml
libs/apps/uesio/studio/bundle/views/manageplan.yaml
libs/apps/uesio/studio/bundle/views/manageplans.yaml

Manage plans if you are an instance admin.
If relevant, explain how to test the change locally

feat: manage plans UI

---

cypress/e2e/route_sanity.cy.ts
cypress/e2e/smoke.cy.ts

Fixes end to end tests that I broke a while ago.

Fix e2e tests from rowaction link mistake

---

apps/platform/pkg/adapt/postgresio/load.go
apps/platform/pkg/datasource/load.go
apps/platform/pkg/types/wire/aggregate.go
apps/platform/pkg/types/wire/field.go
apps/platform/pkg/types/wire/load.go
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/aggregatefieldproptag.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/fieldsproperties.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/groupbyfieldproptag.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/wireproperties.tsx
libs/apps/uesio/studio/bundle/views/packaging.yaml
libs/apps/uesio/tests/bundle/fields/uesio/tests/wire_condition/category.yaml
libs/apps/uesio/tests/hurl_specs/wire_aggregate_load.hurl
libs/apps/uesio/tests/seed_data/wire_conditions.csv
libs/apps/uesio/tests/seed_data/wire_conditions_import.spec.json
libs/ui/src/bands/wire/class.ts
libs/ui/src/bands/wire/operations/initialize.ts
libs/ui/src/definition/wire.ts
libs/ui/src/wireexports.ts

Adds an initial implementation of aggregate wires.

Aggregate wires prototype

---

libs/apps/uesio/io/bundle/componentpacks/calendar/pack.yaml
libs/apps/uesio/io/bundle/componentpacks/calendar/src/components/calendar/calendar.tsx
libs/apps/uesio/io/bundle/components/calendar.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/calendar/default.yaml
package-lock.json
package.json

https://github.com/ues-io/uesio/assets/55447225/8a48dfb6-88ed-4f81-b04c-54100ac6fd4b
Adds version 1 of the calendar component.

Add calendar component

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/table/table.tsx
libs/apps/uesio/io/bundle/components/sitenav.yaml
libs/ui/src/bands/component/signals.ts
libs/ui/src/bands/wire/operations/markfordelete.ts
libs/ui/src/context/context.ts
libs/ui/src/definition/signal.ts

Adds basic multi-record context functionality.

Add multi-record context

---

apps/platform/pkg/adapt/postgresio/postgresio.go
apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/cognito/cognitoauth.go
apps/platform/pkg/auth/google/googleauth.go
apps/platform/pkg/auth/login.go
apps/platform/pkg/auth/mock/mockauth.go
apps/platform/pkg/auth/platform/platform.go
apps/platform/pkg/auth/samlauth/samlauth.go
apps/platform/pkg/auth/samlauth/samlutils.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/controller/login.go
apps/platform/pkg/meta/credential.go
apps/platform/pkg/types/credentials/saml.go
libs/apps/uesio/studio/bundle/fields/uesio/studio/credential/saml.yaml

Adds the ability to us a SAML idp to authenticate to uesio.

Add basic saml functionality

---

libs/apps/uesio/studio/bundle/permissionsets/standard.yaml
libs/apps/uesio/studio/bundle/routes/org.yaml
libs/apps/uesio/studio/bundle/routes/orgusage.yaml
libs/apps/uesio/studio/bundle/routes/userusage.yaml
libs/apps/uesio/studio/bundle/selectlists/usagemetadatatype.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml
libs/apps/uesio/studio/bundle/views/org.yaml
libs/apps/uesio/studio/bundle/views/orgprofilenav.yaml
libs/apps/uesio/studio/bundle/views/orgusage.yaml
libs/apps/uesio/studio/bundle/views/userprofilenav.yaml
libs/apps/uesio/studio/bundle/views/userusage_inner.yaml

Improves the usage views and adds a usage view for organizations.

Improvements to usage views

---

libs/ui/src/component/display.ts

Removes duplicate display condition types.

remove duplicate display condition types

---

apps/platform/pkg/datasource/load.go
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/field.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/reference.tsx

Allows displaying maps as references.

Allow displaying maps as references

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/dialog/dialog.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/sidepanel/sidepanel.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dialog/dialog.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dialogplain/dialogplain.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/sidepanel/sidepanel.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/sidepanelplain/sidepanelplain.tsx
libs/apps/uesio/io/bundle/components/dialog.yaml
libs/apps/uesio/io/bundle/components/sidepanel.yaml

Adds the option to configure whether to close dialogs and sidepanels on outside click.

Add close on outside click option

---

apps/platform/pkg/bot/jsdialect/savebot.go
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/field.tsx
libs/ui/src/public_types/server/index.d.ts

Render maps as codefield

---

apps/platform/pkg/bot/systemdialect/namespaceswap.go
libs/apps/uesio/io/bundle/componentpacks/main/src/components/table/table.tsx
libs/apps/uesio/studio/bundle/views/officialbundlelisting.yaml

make namespace swap readonly

---

apps/platform/pkg/bot/jsdialect/aftersave.go
apps/platform/pkg/bot/jsdialect/beforesave.go
libs/ui/src/bands/route/utils.ts
libs/ui/src/bands/wire/class.ts
libs/ui/src/bands/wire/index.ts
libs/ui/src/bands/wirerecord/class.ts
libs/ui/src/public_types/client/index.d.ts
libs/ui/src/public_types/server/index.d.ts

Better types and add back files band

Better types and add back files band

---

apps/platform/pkg/cmd/serve.go
apps/platform/pkg/deploy/deploy.go
libs/ui/src/component/display.ts

Fix record is new display condition

Fix record is new display condition

---

apps/platform/pkg/datasource/integ.go

Better error message for debugging

add better error message

---

apps/platform/pkg/configstore/platform/platform.go
apps/platform/pkg/datasource/integ.go

Even more error logging for debugging

---

apps/platform/pkg/adapt/postgresio/load.go
apps/platform/pkg/auth/auth.go
apps/platform/pkg/configstore/configstore.go
apps/platform/pkg/configstore/configstore_test.go
apps/platform/pkg/configstore/environment/environment.go
apps/platform/pkg/configstore/platform/platform.go
apps/platform/pkg/controller/configvalue.go
apps/platform/pkg/meta/component.go
apps/platform/pkg/routing/deps.go
libs/apps/uesio/studio/bundle/bots/listener/signup/bot.ts
libs/apps/uesio/studio/bundle/configvalues/signup_notify_email.yaml
libs/apps/uesio/tests/hurl_specs/impersonation.hurl
libs/apps/uesio/tests/hurl_specs/object_and_field_level_security_public_user.hurl
libs/apps/uesio/tests/hurl_specs/record_token_refresh.hurl
libs/apps/uesio/tests/hurl_specs/wire_load_novaluebehavior_condition.hurl

Adds a signup notification email to the studio.

Add signup notification email

---

apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/createlogin.go
apps/platform/pkg/auth/session.go
apps/platform/pkg/datasource/metadatarequest.go
apps/platform/pkg/reflecttool/set.go
apps/platform/pkg/types/wire/load.go

make less reference queries

---

apps/platform/pkg/cmd/serve.go
apps/platform/pkg/controller/file/componentpack.go
apps/platform/pkg/controller/mergedata.go
apps/platform/pkg/controller/mergedata_test.go
apps/platform/pkg/meta/componentpack.go
apps/platform/platform/index.gohtml
libs/apps/uesio/studio/bundle/fields/uesio/studio/componentpack/has_styles.yaml

Adds the ability for component packs to include css files.

Add Css handling to component packs

---

apps/platform/pkg/adapt/postgresio/load.go
apps/platform/pkg/controller/devperfstats.go
apps/platform/pkg/controller/filejson/respondjson.go
libs/apps/uesio/tests/hurl_specs_single_run/perf_stats.hurl

Lists queries by collection in the integration tests query stats.

Better Query stats on integration tests

---

apps/platform/main.go
apps/platform/pkg/bot/declarativedialect/declarativedialect.go
apps/platform/pkg/bot/dialects.go
apps/platform/pkg/bot/systemdialect/systemdialect.go
apps/platform/pkg/meta/bot.go
libs/apps/uesio/core/bundle/bots/generator/bot/bot.js
libs/apps/uesio/core/bundle/bots/generator/bot/bot.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/aftersave/bot.template.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/beforesave/bot.template.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/listener/bot.template.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/load/bot.template.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/route/bot.template.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/runaction/bot.template.yaml
libs/apps/uesio/core/bundle/bots/generator/bot/templates/save/bot.template.yaml
libs/apps/uesio/core/bundle/selectlists/botdialect.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/bot/definition.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/bot/dialect.yaml
libs/apps/uesio/studio/bundle/selectlists/botdialect.yaml
libs/apps/uesio/studio/bundle/views/bot.yaml

Add declarative bots structure and prototype

add basic declarative bots prototype

---

libs/apps/uesio/io/bundle/componentpacks/flow/pack.yaml
libs/apps/uesio/io/bundle/componentpacks/flow/src/utilities/flow/flow.tsx
libs/apps/uesio/io/bundle/componentpacks/flow/src/utilities/flowhandle/flowhandle.tsx
libs/apps/uesio/io/bundle/utilities/flow.yaml
libs/apps/uesio/io/bundle/utilities/flowhandle.yaml
package-lock.json
package.json

Adds the react flow utility component.

add flow utility

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/defapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/api/stateapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/componentinstanceproperties.tsx
libs/ui/src/bands/component/selectors.ts
libs/ui/src/componentexports.ts
libs/ui/src/hooks/componentapi.ts

Caches yaml parses of the same object.

more builder perf improvements

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dialogplain/dialogplain.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/sidepanelplain/sidepanelplain.tsx
libs/ui/src/definition/panel.ts

Fixes a regression where panels were closing too often in the builder.

Fix panel builder experience

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/codepanel.tsx
package-lock.json
package.json

1. updates the yaml library for some bug fixes.
2. makes the selected decorations for the yaml editor appear behind selected text.

update yaml lib

---

libs/apps/uesio/io/bundle/components/table.yaml

adds the icon prop to row actions

Add icon prop to row actions

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/table/table.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/toolbar/toolbar.tsx
libs/apps/uesio/io/bundle/components/toolbar.yaml
libs/ui/src/bands/wire/operations/unmarkfordelete.ts
libs/ui/src/context/merge.ts

Allows for listening to component state in merge syntax $ComponentState

Listen for component state

---

libs/apps/uesio/core/bundle/bots/generator/bot/bot.js
libs/apps/uesio/io/bundle/componentpacks/main/src/components/button/button.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/icon/icon.tsx

Fixes an issue where the bot.ts file was not getting created when creating a new typescript bot.

Small fix for bot creation typescript

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/table/table.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/number.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/readonly.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/reference.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/text.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/textarea.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/table/table.tsx
libs/apps/uesio/io/bundle/componentvariants/uesio/io/customselectfield/default.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/field/default.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/fieldwrapper/table.yaml

Fixes some bugs with the display of listview fields in tables.

Fix listview bugs

---

cypress/support/commands.ts
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/text.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/menu/menu.tsx
libs/ui/src/styles/interpolate.ts
libs/ui/src/styles/styles.ts

Some small fixes for render performance.

Slightly improve render perf

---

apps/platform/pkg/adapt/postgresio/conditions.go
apps/platform/pkg/adapt/postgresio/dateconditions.go
apps/platform/pkg/formula/formulafield.go

You can now use `NOW` in datetime conditions.

Improved datetime conditions

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/autocompletefield/autocompletefield.tsx
libs/apps/uesio/builder/bundle/components/stylesproperty.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/components/menu/menu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/customselect/customselect.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/listmenu/listmenu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/menubutton/menubutton.tsx
libs/apps/uesio/io/bundle/components/field.yaml
libs/apps/uesio/io/bundle/components/menu.yaml
libs/apps/uesio/io/bundle/components/table.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/listmenu/default.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/menu/default.yaml
libs/apps/uesio/io/bundle/utilities/listmenu.yaml
libs/apps/uesio/io/bundle/utilities/menu.yaml
libs/apps/uesio/studio/bundle/components/datamanager.yaml
libs/apps/uesio/studio/bundle/components/generatoractiontile.yaml
libs/apps/uesio/studio/bundle/components/generatorbutton.yaml
libs/apps/uesio/studio/bundle/components/previewbutton.yaml
libs/apps/uesio/studio/bundle/components/recorddatamanager.yaml

Adds a menu component with `trigger` and `content` slots.

Add menu component

---

apps/platform/pkg/adapt/postgresio/load.go

Fixes user pictures in workspaces

Fix user pictures in workspaces

---

apps/platform/pkg/datasource/load.go
libs/apps/uesio/io/bundle/componentpacks/main/src/components/searchbox/searchbox.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/tablabels/tablabels.tsx
libs/apps/uesio/tests/hurl_specs/wire_load_novaluebehavior_condition.hurl
libs/ui/src/bands/wire/conditions/conditions.ts
libs/ui/src/bands/wire/operations/search.ts
libs/ui/src/bands/wire/signals.ts
libs/ui/src/context/merge.ts
libs/ui/src/wireexports.ts
libs/ui/test/wire/search.spec.ts

Adds novalue behavior to search.

Add no value behavior to search

---

apps/platform/pkg/bot/jsdialect/aftersave.go
apps/platform/pkg/bot/jsdialect/apihelpers.go
apps/platform/pkg/bot/jsdialect/asadminapi.go
apps/platform/pkg/bot/jsdialect/beforesave.go
apps/platform/pkg/bot/jsdialect/callbot.go
apps/platform/pkg/bot/jsdialect/routebotapi.go
libs/ui/src/public_types/server/index.d.ts

Adds the save result to the bot.save api.

Add bot save result

---

libs/ui/src/context/merge.ts

Adds `id` to `$Collection` merge.

Add id to collection merge

---

apps/platform/pkg/adapt/postgresio/conditions.go
libs/apps/uesio/tests/hurl_fields/number.hurl
libs/apps/uesio/tests/hurl_fields/reference.hurl
libs/apps/uesio/tests/hurl_fields/select.hurl
libs/apps/uesio/tests/hurl_fields/user.hurl
libs/apps/uesio/tests/hurl_specs/wire_load.hurl
libs/apps/uesio/tests/hurl_specs/wire_load_lookup_condition.hurl
libs/apps/uesio/tests/hurl_specs/wire_load_subquery_condition.hurl
package-lock.json
package.json

`NOT_IN` conditions were not returning null values.

Fix nulls in not in

---

package-lock.json
package.json

revert hurl upgrade

---

apps/platform/pkg/formula/formulafield.go
libs/apps/uesio/io/bundle/componentpacks/main/src/shared/useControlledFieldValue.tsx
libs/ui/src/bands/wire/operations/reset.ts
libs/ui/src/context/merge.ts

Adds a `TO_NUMBER` formula function

Add to number formula function

---

apps/platform/pkg/bot/jsdialect/callbot.go
apps/platform/pkg/bot/jsdialect/jsdialect.go
apps/platform/pkg/bot/jsdialect/loadbot.go
apps/platform/pkg/bot/tsdialect/tsdialect.go
libs/apps/uesio/tests/hurl_specs/listener_bot_custom_integration_action.hurl
libs/apps/uesio/tests/hurl_specs/prevent_querying_secret_store_values.hurl

Call bots now return errors to the user.

Improve call bot error handling

---

apps/platform/pkg/bot/jsdialect/aftersave.go
apps/platform/pkg/bot/jsdialect/apihelpers.go
apps/platform/pkg/bot/jsdialect/asadminapi.go
apps/platform/pkg/bot/jsdialect/beforesave.go
apps/platform/pkg/bot/jsdialect/callbot.go
apps/platform/pkg/bot/jsdialect/routebotapi.go
apps/platform/pkg/types/wire/save.go
libs/ui/src/public_types/server/index.d.ts

You can now add an option to bot saves to do an upsert.

Add upsert option to bot saves

---

apps/platform/pkg/auth/session.go
apps/platform/pkg/bot/systemdialect/systembot_listener_createapikey.go
apps/platform/pkg/bot/systemdialect/systemdialect.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/meta/loginmethod.go
apps/platform/pkg/middleware/authenticate.go
libs/apps/uesio/core/bundle/fields/uesio/core/loginmethod/api_key_name.yaml
libs/apps/uesio/studio/bundle/views/user.yaml
libs/apps/uesio/tests/hurl_seeds/app_and_workspace.hurl
libs/apps/uesio/tests/hurl_specs/api_token.hurl

Adds the ability to create api tokens for a user and authenticate with them.

add api token auth

---

apps/platform/pkg/datasource/bots.go
apps/platform/pkg/meta/bot.go
libs/apps/uesio/studio/bundle/views/apppublish.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml

Actually checks the integration actions params when running an integration action. Instead of the bot's params.

Small bugfixes integration action param check

---

.github/workflows/branch_build.yaml
.github/workflows/master_branch_build.yaml
.github/workflows/release.yaml

updates the version of the git-checkout action

update git checkout version

---

apps/platform/pkg/routing/deps.go
libs/apps/uesio/appkit/bundle/components/icontile.yaml
libs/apps/uesio/appkit/bundle/components/tile_user.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/avatar/breadcrumb.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/group/breadcrumbs.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/scrollpanel/sidebar.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/tile/breadcrumb.yaml
libs/apps/uesio/appkit/bundle/views/tab_ai_threads.yaml
libs/apps/uesio/appkit/bundle/views/user_list_content.yaml
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/headercrumbs.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainheader.tsx
libs/apps/uesio/builder/bundle/components/breadcrumb.yaml
libs/apps/uesio/builder/bundle/components/icontile.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/components/item/item.tsx
libs/apps/uesio/io/bundle/components/deck.yaml
libs/apps/uesio/io/bundle/components/navsection.yaml
libs/apps/uesio/studio/bundle/bundle.yaml
libs/apps/uesio/studio/bundle/views/appcrumb.yaml
libs/apps/uesio/studio/bundle/views/crumbsbar.yaml
libs/ui/src/bands/wire/index.ts
libs/ui/src/hooks/wireapi.ts

1. Move breadcrumb code to appkit.
2. Fix a bug in variant dependency loading.

Breadcrumb refresh

---

apps/cli/go.mod
apps/cli/go.sum
apps/cli/pkg/config/app.go
apps/cli/pkg/localbundlestore/localbundlestore.go
apps/cli/pkg/pack/entryfiles.go
apps/cli/pkg/param/param.go
apps/platform/pkg/bundlestore/filebundlestore/filebundlestore.go
apps/platform/pkg/bundlestore/platformbundlestore/platformbundlestore.go
apps/platform/pkg/bundlestore/systembundlestore/systembundlestore.go
apps/platform/pkg/controller/file/vendor.go

1. Refactors platformbundlestore, systembundlestore and localbundlestore into a single code path.
2. Parallelizes bundestore file writes.

parallelize bundlestore file writes

---

libs/apps/uesio/appkit/bundle/components/form_new.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/scrollpanel/selectcard.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/scrollpanel/selectcard_selected.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/components/scrollpanel/scrollpanel.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/scrollpanel/scrollpanel.tsx
libs/apps/uesio/io/bundle/components/card.yaml
libs/apps/uesio/studio/bundle/featureflags/use_starter_templates.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/app/description.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/app/starter_template.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/bundlelisting/show_starter_template.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/bundlelisting/starter_template_description.yaml
libs/apps/uesio/studio/bundle/views/app_new.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml
libs/apps/uesio/studio/bundle/views/sitemanageappbundles.yaml

New new page with starter template.

New new page with starter template

---

apps/platform/pkg/bot/params.go
apps/platform/pkg/bot/systemdialect/systembot_after_app.go
apps/platform/pkg/bot/systemdialect/systembot_listener_getstarterparams.go
apps/platform/pkg/bot/systemdialect/systembot_listener_workspacetruncate.go
apps/platform/pkg/bot/systemdialect/systemdialect.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/controller/getbotparams.go
apps/platform/pkg/controller/integrationaction.go
libs/apps/uesio/appkit/bundle/bots/generator/home/bot.js
libs/apps/uesio/appkit/bundle/bots/generator/home/bot.yaml
libs/apps/uesio/appkit/bundle/bots/generator/home/templates/home.yaml
libs/apps/uesio/appkit/bundle/bots/generator/leftnav/bot.js
libs/apps/uesio/appkit/bundle/bots/generator/leftnav/bot.yaml
libs/apps/uesio/appkit/bundle/bots/generator/leftnav/templates/leftnav.yaml
libs/apps/uesio/appkit/bundle/bots/generator/starter/bot.js
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dynamicform/dynamicform.tsx
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/generatoractiontile/generatoractiontile.tsx
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/generatorbutton/generatorbutton.tsx
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/generatorstarter/generatorstarter.tsx
libs/apps/uesio/studio/bundle/components/generatorstarter.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/app/starter_template_params.yaml
libs/apps/uesio/studio/bundle/permissionsets/standard.yaml
libs/apps/uesio/studio/bundle/views/app_new.yaml
libs/ui/src/bands/wire/operations/updaterecord.ts
libs/ui/src/hooks/botapi.ts
libs/ui/src/hooks/useplatformfunc.ts

Parameters can now be set for starter templates.

Allow starter template params

---

libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/titlebar/item.yaml
libs/apps/uesio/builder/bundle/componentpacks/main/src/api/signalsapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/bot.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/component.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/integration.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/panel.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/route.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/wire.ts
libs/apps/uesio/studio/bundle/fields/uesio/studio/sitedomain/type.yaml
libs/apps/uesio/studio/bundle/permissionsets/standard.yaml
libs/apps/uesio/studio/bundle/routes/sitesettings.yaml
libs/apps/uesio/studio/bundle/routes/workspaceconfig.yaml
libs/apps/uesio/studio/bundle/routes/workspacesettings.yaml
libs/apps/uesio/studio/bundle/views/app.yaml
libs/apps/uesio/studio/bundle/views/domains.yaml
libs/apps/uesio/studio/bundle/views/site.yaml
libs/apps/uesio/studio/bundle/views/sitenav.yaml
libs/apps/uesio/studio/bundle/views/sitesettings.yaml
libs/apps/uesio/studio/bundle/views/workspacesettings.yaml
libs/ui/src/componentexports.ts
libs/ui/src/definition/signal.ts
libs/ui/src/signals/signals.ts

1. Adds signal conditions
2. Adds a settings page to the site sidebar nav. (For consistency with app and workspace)

site settings refactor

---

libs/apps/uesio/io/bundle/components/table.yaml

Add the option to the table properties to show row numbers for the table.

add row numbers option

---

apps/platform/pkg/bot/systemdialect/systembot_before_field.go
libs/apps/uesio/tests/hurl_specs/collection_fields_lifecycle.hurl

Adds test for editing reference fields.
NOTE: I haven't done the fix yet, just the failing test.

Add failing test

---

cypress/support/commands.ts
libs/apps/uesio/appkit/bundle/views/login_mock.yaml
scripts/run-integration-tests.sh

Fixes the integration and e2e tests that were failing because of the previous PR with mock-login changes.

fix tests from mock changes

---

libs/apps/uesio/sitekit/bundle/componentvariants/uesio/io/box/section_inner_content.yaml

Small styling change needed for the uesio website.

remove sitekit section content styles

---

libs/ui/src/bands/component/signals.ts

This fixes an eslint error that we're getting with the upcoming eslint improvements.

Fixes no-loop-func eslint error

---

eslint.config.mjs
libs/apps/uesio/aikit/eslint.config.mjs
libs/apps/uesio/appkit/eslint.config.mjs
libs/apps/uesio/builder/eslint.config.mjs
libs/apps/uesio/core/bundle/bots/generator/init/templates/template.eslint.config.mjs
libs/apps/uesio/core/bundle/bots/generator/init/templates/template.package.json
libs/apps/uesio/core/eslint.config.mjs
libs/apps/uesio/io/eslint.config.mjs
libs/apps/uesio/sitekit/eslint.config.mjs
libs/apps/uesio/studio/eslint.config.mjs
libs/ui/eslint.config.mjs
package-lock.json
package.json

chore: lint json files

---

libs/apps/uesio/core/bundle/bots/generator/bot/templates/aftersave/bot.template.ts
libs/apps/uesio/core/bundle/bots/generator/bot/templates/beforesave/bot.template.ts
libs/apps/uesio/core/bundle/bots/generator/bot/templates/listener/bot.template.ts
libs/apps/uesio/core/bundle/bots/generator/bot/templates/load/bot.template.ts
libs/apps/uesio/core/bundle/bots/generator/bot/templates/route/bot.template.ts
libs/apps/uesio/core/bundle/bots/generator/bot/templates/runaction/bot.template.ts
libs/apps/uesio/core/bundle/bots/generator/bot/templates/save/bot.template.ts

fixed formatting in some templates

chore: fix template formatting

---

scripts/run-all-tests-ci.sh
scripts/run-all-tests.sh

Run unit tests during npm test scripts (e.g., run-all-tests, run-all-tests-ci)
tested locally, all works.

chore: run unit tests in test scripts

---

eslint.config.mjs
libs/apps/uesio/aikit/eslint.config.mjs
libs/apps/uesio/appkit/eslint.config.mjs
libs/apps/uesio/builder/eslint.config.mjs
libs/apps/uesio/core/bundle/bots/generator/init/templates/template.eslint.config.mjs
libs/apps/uesio/core/bundle/bots/generator/init/templates/template.package.json
libs/apps/uesio/core/eslint.config.mjs
libs/apps/uesio/io/eslint.config.mjs
libs/apps/uesio/sitekit/eslint.config.mjs
libs/apps/uesio/studio/eslint.config.mjs
libs/ui/eslint.config.mjs
package-lock.json
package.json

add yaml files to linting
e2e & ci should cover.

chore: add yaml files to linting

---

eslint.config.mjs
tsconfig.json

Support linting of all non-project files

chore: lint non-project files

---

libs/vendor/eslint.config.cjs
libs/vendor/eslint.config.mjs
libs/vendor/files/react/umd/react-jsx-runtime.production.min.js
libs/vendor/project.json
libs/vendor/tsconfig.json
libs/vendor/tsconfig.lib.json
libs/vendor/tsconfig.spec.json

Adds linting to vendor project

chore: lint vendor project

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/viewlayout/viewlayout.tsx

Adds semantic html tags `main`, `header` and `footer` to the `uesio/io.viewlayout` component.

semantic tags for viewlayout

---

.github/workflows/ci.yaml

Add base ci workflow - more coming....
manual testing to occur once its in main branch.

chore: add new ci workflow

---

libs/apps/uesio/builder/jest.config.ts

Fix coverageDirectory path typo.

chore: fix path typo

---

.github/workflows/ci.yaml

Make sure all tags are pushed to ECR.
ci and e2e will cover.

chore: push --all-tags

---

.github/workflows/release.yaml

update workflow permissions
workflow itself will be the test

chore: update workflow permissions

---

.github/workflows/release.yaml

chore: update workflow step name

---

libs/apps/uesio/studio/bundle/fields/uesio/studio/blogentry/category.yaml
libs/apps/uesio/studio/bundle/views/homecontent.yaml

Fixes the news links on the home page.

Fix homepage news links

---

apps/platform/pkg/datasource/load.go
apps/platform/pkg/datasource/load_metadata.go

Cleans up datasource load some more to better support adding load errors to individual wires.
https://github.com/ues-io/uesio/pull/4576

more datasource load refactoring

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/selectborder.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/declarativecomponentslotloader/declarativecomponentslotloader.tsx
libs/ui/src/component/component.spec.tsx
libs/ui/src/components/slot.tsx
libs/ui/src/context/merge.ts

Under certain circumstances, we were not wrapping declarative slots in the correct buildwrapper context. This fixes that.

Fix declarative slot selection issues

---

libs/apps/uesio/studio/bundle/views/homecontent.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml

Removes the old splash image from the home screen.

Rebrand home screen

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexpanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexslot.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/selectborder.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/dragdrop.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/buildwrapper/buildwrapper.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/placeholder/placeholder.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/propnodetag/propnodetag.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/slotbuilder/slotbuilder.tsx
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/tile/indextag.yaml
libs/ui/src/component/component.tsx

Improves drag-drop functionality.
1. Adds a throttle to the drag handler so that it only runs at most once every 200ms.
2. Fixes various bugs with determining the correct index of a drag location.

Builder ux improve drag and drop

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_draggable.tsx

make buildbar draggable.

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_draggable.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_tools.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/listmenu/listmenu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/menubutton/menubutton.tsx
libs/apps/uesio/io/bundle/utilities/menubutton.yaml
libs/ui/src/context/context.ts

Adds the ability to toggle the code panel and the index panel from the build bar.

Add buildbar view toggle menu

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/markdownfield/markdownfield.tsx
package-lock.json
package.json

Updates react-markdown major to 10.0.0.
Manual testing all passes.

chore: update react-markdown major to 10.0.0

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dynamictable/dynamictable.tsx
libs/apps/uesio/sitekit/bundle/bots/generator/view_landing/bot.js
libs/apps/uesio/sitekit/bundle/bots/generator/view_landing/bot.yaml
libs/apps/uesio/sitekit/bundle/bots/generator/view_landing/templates/landing.yaml
libs/apps/uesio/sitekit/bundle/components/section.yaml
libs/apps/uesio/sitekit/bundle/components/section_hero.yaml
libs/apps/uesio/sitekit/bundle/componentvariants/uesio/io/box/section_inner_content_form.yaml
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/multipermissionpicker/multipermissionpicker.tsx
libs/apps/uesio/studio/bundle/components/multipermissionpicker.yaml
libs/apps/uesio/studio/bundle/components/permissionmapeditor.yaml
libs/apps/uesio/studio/bundle/views/permissionset.yaml
libs/apps/uesio/studio/bundle/views/profile.yaml

1. Adds a generator to sitekit for creating landing pages
2. Cleans up the profile detail page
3. Cleans up the permission set detail page

Add sitekit landing page generator

---

apps/cli/pkg/cmd/app.go
apps/cli/pkg/command/app/delete.go
apps/cli/pkg/context/appcontext.go
apps/cli/pkg/wire/app.go

This is trying to develop this new feature https://github.com/ues-io/uesio/issues/4575 
Manually testing required here in the CLI use this command 
`uesio app delete -n abel/dogs`
or 
`uesio app delete`
and it will ask you which application you want to delete

feat: add app delete command

---

README.md

chore: format readme

---

libs/apps/uesio/studio/bundle/featureflags/manage_bots.yaml
libs/apps/uesio/studio/bundle/featureflags/manage_components.yaml
libs/apps/uesio/studio/bundle/featureflags/manage_feature_flags.yaml
libs/apps/uesio/studio/bundle/featureflags/manage_integration_types.yaml
libs/apps/uesio/studio/bundle/featureflags/manage_integrations.yaml
libs/apps/uesio/studio/bundle/featureflags/manage_user_access_tokens.yaml

Turns on 6 feature flags by default as requested by @greggthebax

Change studio feature flag defaults

---

package-lock.json
package.json

chore: update npm minor deps

---

libs/apps/uesio/core/bundle/files/favicon/uesiofav.svg

This just updates our favicon image to a simpler svg file. (it doesn't have the weird crooked lines in it that has been bothering me)

update favicon to simpler svg

---

package-lock.json
package.json

Fixes some vulnerabilities on the `npm audit`

chore: minor npm deps update

---

libs/vendor/README.md

Updates vendor project readme with manifest sample based on recent updates to that file.
doc update only.

chore: update readme

---

apps/platform-integration-tests/hurl_fields/user.hurl

Update hurl todo comment for https://github.com/Orange-OpenSource/hurl/issues/3869
doc only.

chore: update hurl TODO comment

---

apps/platform-integration-tests/hurl_specs/component_dependencies.hurl
apps/platform-integration-tests/hurl_specs/componentpack_download.hurl
apps/platform-integration-tests/hurl_specs/file_download.hurl
apps/platform-integration-tests/hurl_specs/font_download.hurl
apps/platform-integration-tests/hurl_specs/listener_bot.hurl
apps/platform-integration-tests/hurl_specs/wire_load_userfile.hurl
apps/platform/pkg/adapt/postgresio/errors.go
apps/platform/pkg/bot/jsdialect/bothttpapi.go
apps/platform/pkg/bot/jsdialect/routebotapi.go
apps/platform/pkg/bundlestore/filebundlestore/filebundlestore.go
apps/platform/pkg/controller/file/serve_file.go
apps/platform/pkg/controller/oauth/callback.go
apps/platform/pkg/controller/route.go
apps/platform/pkg/controller/save.go
apps/platform/pkg/datasource/bots.go
apps/platform/pkg/datasource/integ.go
apps/platform/pkg/datasource/metadatarequest.go
apps/platform/pkg/datasource/save.go
apps/platform/pkg/fileadapt/localfiles/localfiles.go
apps/platform/pkg/fileadapt/s3/download.go
apps/platform/pkg/integ/bedrock/bedrock.go
apps/platform/pkg/oauth2/client.go
apps/platform/pkg/routing/deps.go
apps/platform/pkg/routing/routing.go
apps/platform/pkg/types/exceptions/notfound.go
apps/platform/pkg/types/exceptions/utils.go
libs/apps/uesio/appkit/bundle/components/sidebar.yaml
libs/apps/uesio/io/bundle/components/deck.yaml

1. Fixes issue were HTTP 500 was being returned when file/resource was not found
2. Fixes a few spots in component/view definitions that were misconfigured and pointing to assets that do not exist
3. Eliminates all type assertions on errors and uses errors.Is/As
Manual testing confirms expected behavior.  ci & e2e will cover rest.

fix: handle NotFound errors and refactor all type assertions on errors

---

apps/platform/pkg/datasource/load.go

Missed adding a TODO comment in #4709
comment only.

chore: add http 400/500 todo comment

---

libs/vendor/gulpfile.js

Monaco editor ships source maps in separate folder.  This PR modifies gulpfile to include them for non-dev builds.

chore: ensure monaco-editor sourcemaps are available

---

libs/apps/uesio/core/bundle/bots/generator/init/templates/template.package.json

Updated the `package.json` template (`uesio app init`) to align with current core repo dependency versions.
This file needs to be maintained on an on-going basis with the core repo dependencies.
tested manually with custom component pack.

chore: update generated package.json template

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_tools.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/chatpanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/codepanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/adjustableheightarea/adjustableheightarea.tsx

Adds the chatpanel to the builder UI.
Note: This doesn't actually implement the chat panel functionality. Just adds the panel structure.

Add chat panel builder ui

---

README.md
apps/platform-e2e/cypress.config.mjs
apps/platform-integration-tests/scripts/setup-env.sh
apps/platform/Dockerfile
apps/platform/pkg/cache/redis.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/configstore/environment/environment.go
apps/platform/pkg/controller/mergedata_test.go
apps/platform/pkg/env/primarydomain.go
apps/platform/pkg/middleware/logging.go
apps/platform/pkg/secretstore/environment/environment.go
docker-compose-local.yaml
docker-compose-tests.yaml
docs/deployment/aws-ecs/taskdefinition-web-app.json
docs/deployment/docker-compose/docker-compose.yaml
docs/http_caching.md
libs/ui/src/platform/platform.spec.ts
scripts/run-docker-tests.sh

Modifies all UESIO environment variables to have a `UESIO_` prefix.
Requires coordination with uesio-infra deployment to modify env vars.

chore: `UESIO_` prefix for all environment variables

---

apps/cli/pkg/config/host/host.go

Remove debug statements
Manually tested.

chore: remove debug statements

---

.golangci.yaml
apps/platform/pkg/auth/auth.go
apps/platform/pkg/bot/systemdialect/systembot_load_recentmetadata.go
apps/platform/pkg/creds/aws.go
apps/platform/pkg/datasource/metadatarequest.go
apps/platform/pkg/routing/deps.go

chore: lint add misspell

---

.golangci.yaml
apps/platform/pkg/auth/login.go
apps/platform/pkg/bot/jsdialect/bothttpapi_test.go
apps/platform/pkg/oauth2/authorizationcode_test.go

Adds the canonical header linter

chore: lint add canonicalheader

---

apps/platform/pkg/bundlestore/filebundlestore/filebundlestore.go

Previously, we were only caching bundle metadata items if the user had permission to them. That meant that non-public metadata items were never cached until a user came along that had access. This caused those items to have cache-misses repeatedly.

fix: always cache bundle items

---

libs/apps/uesio/studio/bundle/views/user.yaml

1. Move "Delete User" button to bottom in a "Danger Zone"
2. Ensure form toggles between READ/EDIT mode after save/cancel
3. Apply same styling to buttons as form_detail.yaml to gain come consistency in layout & styling
4. Add `Id` as a form field
Manual testing confirms expected behavior.

chore: user detail view improvements

---

libs/ui/src/context/merge.ts

1. Adds two new merge functions: `$Equals{}` and `$NotEquals{}`. These work in a similar way to the `$StartsWith{}` merge.
2. Merges the expression sent into the `$File{}` merge to support cases like this:
```
$File{$Parent.Record{uesio/studio.namespace}.$Parent.Record{uesio/studio.name}:${uesio/core.path}}
```
3. Allows the `$UserFile{}` merge to work without any expression, but simply getting the UserFile url of the record in context.

Feat: merge improvements $Equals{} and $NotEquals{}

---

libs/ui/src/bands/userfile/signals.ts
libs/ui/src/signals/signals.ts

1. Adds a signal "BAND" for working with userfiles.
2. For now we're just adding the "DELETE" signal.

feat: adds the userfile DELETE signal

---

libs/apps/uesio/core/bundle/bots/generator/init/templates/template.package.json

Sync template package.json dep versions with root repo.
Tested manually and confirmed.

chore: sync template package.json dep versions with root repo

---

apps/platform/pkg/cache/redis.go

Ensures registering a redis namespace is synchronized/protected from concurrent access.

chore: protect redis namespace registration

---

apps/platform/pkg/controller/login.go
apps/platform/pkg/controller/logout.go
apps/platform/pkg/controller/resetpassword.go
apps/platform/pkg/controller/signup.go
apps/platform/pkg/middleware/authenticate.go

A little cleanup and updating of comments based on all the recent auth related PRs - no functional changes.

chore: a little cleanup

---

apps/platform/pkg/bundlestore/platformbundlestore/platformbundlestore.go

Ensures that creation of platform file connection is properly synchronized/protected from concurrent access.

fix: sychronize creating platform file connection

---

apps/cli/go.mod
apps/cli/go.sum
apps/cli/pkg/call/call.go
apps/platform/pkg/auth/session.go
apps/platform/pkg/controller/login.go
apps/platform/pkg/controller/logout.go
apps/platform/pkg/controller/signup.go
apps/platform/pkg/middleware/authenticate.go

Refactors management of browser session from `auth` to `middleware` package.  See #5080 for details.

chore: refactor browser session mgmt to middleware package

---

apps/platform/pkg/bot/systemdialect/systembot_before_sitedomain.go

Improves domain validation error messages to have appropriate context related to if its a "domain" or a "subdomain"
Manually tested and confirmed.

chore: improve domain validation error messages
