ues-io/uesio

libs/apps/uesio/studio/bundle/views/appnav.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml

This is an experiment to see if using route/REDIRECT is a more reliable way to navigate for the purposes of Cypress tests when creating apps and workspaces initially.

fix(tests): Switch to route/REDIRECT for App and Workspace creation

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/canvas.tsx

1. uses onClickCapture in the canvas to cancel any click events there. This way it can use clicking only for selection. All events in the canvas will still work though. But later we can use event capturing to capture those events too if we wanted.
1. The builder should work as before. Selection of components should work, and components in the canvas should not perform their normal behavior when clicked.
2. You should also be able to scroll using your mouse's scrollwheel.

Fix builder scrolling

---

.github/workflows/release.yaml

Modifies the release workflow to be the following:
1. Whenever a new "v*" tag is pushed, e.g. "v1.0.0", this workflow is run. The expectation is that a Github Release will already exist before this happens.
2. CLI assets for each OS/arch are created and then uploaded to the Github Release corresponding to this tag.
3. The existing Docker image in ECR will be pulled and then republished to GHCR with the version tag as well as the "latest" tag

ci: Publish to Github container registry on release tag push

---

.github/workflows/release.yaml

1. Need the id-token permission in order to obtain AWS credentials
2. Ensure that uploaded artifact names don't conflict
3. Remove linux-arm64 binary

fix: Need id-token to load AWS credentials, fix artifact name conflicts

---

.github/workflows/release.yaml

In order to get Windows and Mac release binaries to work, we have to build them, temporarily store them in GH artifacts, then upload them to the GH release separately running on a Linux runner.

ci: Build and upload artifacts separately

---

apps/platform/pkg/auth/site.go
apps/platform/pkg/bot/systemdialect/systembot_load_blogentry.go
apps/platform/pkg/bot/systemdialect/systembot_load_recentdoc.go

Allows the studio to work locally at `localhost:3000`
1. Turn off SSL by setting the `UESIO_USE_HTTPS` environment variable to false.
2. Visit the studio locally at `localhost:3000`

Allow studio to work on localhost

---

.github/workflows/release.yaml

`--all-tags` is unnecessary when requesting a specific tag already.

fix: Remove unnecessary docker pull --all-tags

---

apps/platform/pkg/meta/metadata.go
apps/platform/pkg/reflecttool/tags.go

I came across this while inspecting some information that was stored in redis. There were a lot of null keys for these fields since they weren't queried. Since these are part of every object, it's nice to omit them if they are empty.
Everything should work the same as before.

Omit empty builtin user fields

---

.github/workflows/release.yaml

The publish to GHCR is still failing, this change should fix the latest error from the most recent build.

ci: Add write-all permissions to fix GHCR publish

---

libs/apps/uesio/studio/bundle/permissionsets/admin.yaml
libs/apps/uesio/studio/bundle/routes/admin.yaml
libs/apps/uesio/studio/bundle/routes/sitemanageappbundles.yaml
libs/apps/uesio/studio/bundle/routes/sitemanagebundles.yaml
libs/apps/uesio/studio/bundle/views/admin.yaml
libs/apps/uesio/studio/bundle/views/adminnav.yaml
libs/apps/uesio/studio/bundle/views/profiletag.yaml
libs/apps/uesio/studio/bundle/views/sitemanageappbundles.yaml
libs/apps/uesio/studio/bundle/views/sitemanagebundles.yaml
libs/apps/uesio/studio/bundle/views/sitenav.yaml

1. Adds the instance adminstration section for users with the uesio/studio.admin profile.
2. Moves the manage bundles section out of the site management settings.
This is preparing the way for a new section where you can add bundles from an external or "prod" bundlestore.
Manage bundles should work the same as before.

Adds instance administration section

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/stateapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/canvas.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/popper/popper.tsx

Fixes #3807 . You should now be able to select on-close signals for a panel.
Follow the repro steps in #3807 You should no longer be able to repro this.

Fix select with a panel behind it auto-closing

---

apps/platform/pkg/datasource/builtin.go
apps/platform/pkg/datasource/metadata.go

We were getting a `fatal error: concurrent map writes` error when using MULTI-REFERENCE fields in production. The issue is that we were writing to this Fields map on the collection metadata concurrently.
This PR changes it so that a new Fields map is created every time we get common field metadata.

Fix race condition for common fields

---

libs/apps/uesio/core/bundle/bots/generator/bot/bot.js

I wasn't able to create an after-save bot, I think Goja doesn't support the replaceAll function.
In any case, I think we don't need to replace all since a collection should be **_WWW/KKK.QQQ_**
Try to create an after-save bot

fix: unable to create collection after save bots

---

apps/platform/pkg/bot/systemdialect/systembot_listener_addexternalbundle.go
apps/platform/pkg/bot/systemdialect/systembot_listener_createbundle.go
apps/platform/pkg/bundlestore/bundlestore.go
apps/platform/pkg/bundlestore/platformbundlestore/platformbundlestore.go
apps/platform/pkg/bundlestore/systembundlestore/systembundlestore.go
apps/platform/pkg/bundlestore/workspacebundlestore/workspacebundlestore.go
apps/platform/pkg/controller/bundlesretrieve.go

1. Consolidates bundle creation code into a single method.
2. Removes the `StoreItem` bundlestore API and adds the `SetBundleZip` api instead.
Test creating a new bundle from a workspace.
Test adding an external bundle from a prod bundlestore.

Simplify Create Bundle

---

apps/platform/pkg/meta/routeassignment.go
apps/platform/pkg/routing/deps.go
apps/platform/pkg/routing/preload.go
libs/ui/src/bands/route/types.ts
libs/ui/src/bands/route/utils.ts
libs/ui/src/bands/routeassignment/index.ts
libs/ui/src/definition/routeassignment.ts
libs/ui/src/store/store.ts

Adds a routeassignment band and sends all route assignments to the client. These route assignments can be used in components for a follow-up PR.
Load a view. Verify in redux-dev-tools that the routeassignment band exists.

Adds Route Assignments to the client

---

libs/apps/uesio/builder/bundle/componentvariants/uesio/io/group/appcrumb.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/titlebar/profile.yaml
libs/apps/uesio/core/bundle/bots/generator/component_nav/templates/nav.yaml
libs/apps/uesio/core/bundle/bots/generator/component_nav/templates/navbutton.yaml
libs/apps/uesio/io/bundle/components/navsection.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/titlebar/nav.yaml
libs/apps/uesio/studio/bundle/componentvariants/uesio/io/scrollpanel/left.yaml
libs/apps/uesio/studio/bundle/componentvariants/uesio/io/tile/appitem.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml

Simplifies studio navigation.
Check out the navigation bar for studio views. Verify that it is an improvement.

improve navigation styling

---

libs/apps/uesio/studio/bundle/fields/uesio/studio/permissionset/integrationactionrefs.yaml
libs/apps/uesio/studio/bundle/views/permissionset.yaml

The integration part in the permission sets UI wasn't working.
I noticed that backend side we have this **_AllowAll    bool            `yaml:"allowAllActions" json:"allowAllActions"`_** for the IntegrationPermission meaning that on the frontend side is called **allowAllActions** while the backend side is called **allowAll**.  This should fix it and not create any problems. I can't see any reference in the frontend to this field apart from the permissions. 
If relevant, explain how to test the change locally

fix: Integration Actions in permissionsets UI

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainheader.tsx
libs/apps/uesio/builder/bundle/components/breadcrumb.yaml

This was harder to understand than to fix! 
So I try to explain it to see it clear for you @humandad.
Basically, route/NAVIGATE does a platform.getRoute() that has getViewDefId() the view in context matters for the navigate.
In this builder use case and in the studio use case when we use the breadcrumb I guess we want to keep everything in the studio namespace.
If relevant, explain how to test the change locally

fix: breadcrumb in builder context

---

apps/platform/go.mod
apps/platform/go.sum
apps/platform/pkg/bot/jsdialect/bothttpapi.go
apps/platform/pkg/bot/jsdialect/bothttpapi_test.go

Allows parsing of maps/slices into x-www-form-urlencoded request bodies. (This just uses the stripe sdk to do this)

add formdata request parsing

---

apps/platform/pkg/adapt/postgresio/load.go
apps/platform/pkg/datasource/load.go
apps/platform/pkg/meta/collection.go
apps/platform/pkg/meta/collection_test.go
apps/platform/pkg/meta/permissionset.go
apps/platform/pkg/types/wire/load.go
apps/platform/pkg/types/wire/metadata.go
libs/apps/uesio/studio/bundle/fields/uesio/studio/collection/idfield.yaml

1. Drops total queries performed during Uesio Integration tests by 25%, by reducing the number of unnecessary record level access queries that Uesio makes by doing a better job of checking to see whether there are collections in a Load request actually needing record level access checks. 
2. Begins to refactor Postgres Load adapter to be able to function against an external PG database other than Uesio's multi-tenant, single-table structure.
3. Adds a new IdField field on Collections, which will be used to identify metadata related to the "id" field of external Postgres Collections.
```
{"queryStats":{"totalWorkspaceQueries":2113,"totalQueries":15841}}
```
```
{"queryStats":{"totalWorkspaceQueries":2103,"totalQueries":12119}}
```
There should be no functional changes to the app at this …

refactor: Start to extract record level access enforcement out of Postgresio adapter

---

libs/apps/uesio/io/bundle/componentpacks/chart/src/shared/aggregate.spec.tsx
libs/apps/uesio/io/bundle/componentpacks/chart/src/shared/aggregate.tsx
libs/apps/uesio/io/bundle/componentpacks/chart/src/shared/labels.tsx
libs/ui/src/bands/wire/operations/initialize.ts
libs/ui/src/definition/wire.ts
libs/ui/src/wireexports.ts

1. Allow SELECT fields to be used in Charts by treating them like TEXT fields.
2. Performs a count on non-numeric value fields.
3. Adds unit tests for the `aggregate` function.
1. Add a chart with a series whose Category Field is a SELECT, and whose Value Field is uesio/core.id. Verify that the values for each Select value are counted.

fix: Support SELECT fields in Chart labels/categories, do count on non-numeric value fields

---

apps/platform/pkg/bot/jsdialect/sessionapi.go
libs/ui/src/public_types/server/index.d.ts

Gives bots access to information about their site.

Add site api to session api for bots

---

libs/ui/src/context/context.ts
libs/ui/src/context/merge.spec.ts
libs/ui/src/context/merge.ts

1. Allows one-level nested merges.
2. Adds the Text merge function that will just return the expression sent to the function.
`$Text{$SignalOutput{[ask][data]}}`

Allow one-level nested merges

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/number.tsx

No longer formats number inputs in edit mode.
This was causing a bug with the cursor shifting.

fix number input cursor issue

---

libs/apps/uesio/studio/bundle/views/homecontent.yaml

Fixes the order of blog entries on the studio home page.
Also increases the number of blog entries shown to 5.

Fix blog entries order

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/checkbox.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/text.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/table/table.tsx
libs/apps/uesio/io/bundle/components/searchbox.yaml
libs/apps/uesio/io/bundle/components/table.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/checkboxfield/default.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/fieldwrapper/table.yaml
libs/ui/src/hooks/signalapi.tsx

Prevents row action default actions from running when editing input elements on that row.

Fix default row action propagation

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/reference.tsx
libs/ui/src/component/display.ts

Fixes and issue where reference filters were not displaying the selected value correctly.

Fix reference filter display bug

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/multiselect.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/multiselectfilter/multiselectfilter.tsx

1. Add the correct placeholder text to multi-select filters.
2. Allow variants to be sent to multi-select filters
3. Correctly handle the blank select option so that it handles both empty string and null values.

multiselect filter improvements

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/emptystate/emptystate.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/titlebar/titlebar.tsx
libs/apps/uesio/io/bundle/components/emptystate.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/emptystate/default.yaml
libs/apps/uesio/studio/bundle/collections/bundlelisting.yaml
libs/apps/uesio/studio/bundle/collections/licensetemplate.yaml
libs/apps/uesio/studio/bundle/components/bundlelistingvisual.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/bundlelisting/splash.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/bundlelisting/title.yaml
libs/apps/uesio/studio/bundle/fields/uesio/studio/externalbundlelisting/title.yaml
libs/apps/uesio/studio/bundle/permissionsets/public.yaml
libs/apps/uesio/studio/bundle/permissionsets/standard.yaml
libs/apps/uesio/studio/bundle/routes/publicbundlelisting.yaml
libs/apps/uesio/studio/bundle/views/apppublish.yaml
libs/apps/uesio/studio/bundle/views/bundlelisting.yaml
libs/apps/uesio/studio/bundle/views/bundlestore.yaml
libs/apps/uesio/studio/bundle/views/officialbundlestore.yaml
libs/apps/uesio/studio/bundle/views/publicbundleheader.yaml
libs/apps/uesio/studio/bundle/views/publicbundlelisting.yaml
libs/apps/uesio/studio/bundle/views/sitemanageappbundles.yaml
libs/apps/uesio/studio/bundle/views/sitemanagebundles.yaml

Adds a public listing page for installable bundles.
With splash image
Without splash image.

Add public bundlestore listings

---

apps/cli/pkg/command/pack.go
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/dataimport/importbutton.tsx
libs/vendor/gulpfile.js
package-lock.json
package.json

This finally fixes the bug where the studio component pack was occasionally failing to load.
Monaco pollutes the global `define` object.
https://github.com/microsoft/monaco-editor/issues/3083
Then papaparse tries to check for a global define object. Papaparse ends up using the monaco loader somehow.

Fix annoying component not found bug

---

apps/platform/pkg/auth/google/googleauth.go
libs/apps/uesio/studio/bundle/bots/listener/signupgoogle/bot.ts
libs/apps/uesio/studio/bundle/bots/listener/signupgoogle/bot.yaml
libs/apps/uesio/studio/bundle/signupmethods/google.yaml

This emails the studio admin when a new user signs up using the Google method.
You can test this locally, by adding the Google and SendGrid keys and ensuring that the config value signup_notify_email is set.
Then just create a new user using the Google method.

send email to admin when a new user signup using google

---

README.md
apps/platform/main.go
apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/cache.go
apps/platform/pkg/cache/memory.go
apps/platform/pkg/cache/platform.go
apps/platform/pkg/cache/redis.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/datasource/fetchreferences.go
apps/platform/pkg/datasource/licensing.go
apps/platform/pkg/datasource/references.go
apps/platform/pkg/datasource/save.go
apps/platform/pkg/middleware/dev_logger.go
apps/platform/pkg/oauth2/authorizationcode.go
apps/platform/pkg/reflecttool/set.go
apps/platform/pkg/types/wire/save.go
apps/platform/pkg/usage/usage.go
apps/platform/pkg/usage/usage_common/usage_common.go
apps/platform/pkg/usage/usage_memory/usage_memory.go
apps/platform/pkg/usage/usage_redis/usage_redis.go
cypress/e2e/builder.cy.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/canvas.tsx
libs/apps/uesio/tests/hurl_specs/wire_save.hurl

1. Added environment variable documentation for REDIS and UESIO_DB settings.
2. Created an in-memory usage handler that does not need Redis.
3. Added a `UESIO_WORKER_MODE` setting to allow the worker to run on the same process as the webserver.
These changes allow uesio to run with full functionality on a single server without Redis.

allow uesio to run without redis

---

README.md
libs/apps/uesio/core/bundle/files/favicon/uesiofav.svg

Resolves #4352 
- README logo properly displays in dark & light mode
- favicon in browser displays correctly based on browser theme when running ues locally

fix: display of favicon & README logo in dark mode

---

.vscode/extensions.json
nx.json

Removes all references to tslint in nx config and vscode config. We aren't using it anyway.

Remove tslint references

---

libs/apps/uesio/io/bundle/componentpacks/main/src/components/viewlayout/viewlayout.tsx

This prevents the entire view from re-rendering when the header scroll direction has changed.

prevent full view rerender on header direction

---

libs/apps/uesio/studio/bundle/views/file.yaml
libs/ui/src/context/merge.ts

Allows pre-merging the expression inside of a `$Currency{}` merge. That way you can use the result of a `$Formula{}` merge as the expression.

improve currency merge

---

jest.config.js
scripts/tests-cleanup.sh
scripts/tests-init.sh

1. Switches back to the deprecated `getJestProjects()` function. This is so that the jest extension in vscode will work. We could switch back to the `getJestProjectsAsync()` function at some point, but that would take some more work getting the config files to handle `async/await`
2. Uses an alias instead of the `PATH` environment variable in scripts.

use alias instead of path

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/paramsfield/paramsfield.tsx
libs/ui/src/bands/view/operations/load.ts
libs/ui/src/components/view.tsx
libs/ui/src/components/wires.tsx

Ensures that a view component does not display an error when no view is selected and properly displays when selected.
Resolves #4369
Manual testing of scenarios described in #4369 including monitoring for number of network calls resulting from memoized result.
@humandad - Couple of things specifically for review beyond general:
1. If the network call fails, error displays in console due to unhandled rejection occuring in useEffect which isn't ideal.  LIkely better to have the component itself display an error possibly.  Not sure what the standard is in the codebase for these types of situations.  Thoughts?
2. Regarding the Wires component, I tried to find & identify how FunctionComponents are defined in other areas and follow similar/same pattern.  It's a little overkill since Wires will …

fix: view component not loading correctly

---

libs/ui/src/context/merge.spec.ts
libs/ui/src/context/merge.ts

There was a bug when using the `$Currency{<myvalue>}` merge without a second parameter. It was throwing an error due to trying to run `parseInt` on `undefined`.
This PR fixes that and adds a few simple tests.

Fix currency merge and add tests

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexslot.tsx

If a slot does not specify a `label` property, display the `name` of the slot so that the component index contains something meaningful rather than `Slot` so that the user knows which slot is which.
No current test coverage so manual testing of the builder on a component that does not contain labels for slots (e.g., Card).
Resolves #4409

fix: display slot name when label not provided

---

apps/cli/pkg/command/workspace/deploy.go
apps/cli/pkg/command/workspace/retrieve.go

When `-d` is not specified for `retrieve` or `deploy` commands, ensure log message contains "current directory"
> [!NOTE]
> There are several issues with the way that paths are resolved when `-d` is specified.  For example, if `./` is specified, retrieve fails with `Error: illegal file path: bundle/views/community_detail.yaml` error.  This PR only addresses the specific case around not specifying `-d`.  Separately, the entire code base should be reviewed/adjusted to ensure proper handling of `-d` depending on the approach taken in #4393.
No existing tests so manual testing performed to ensure proper message emitted.
Resolves #4402

fix: log message when `-d` option is not specified

---

apps/cli/pkg/zip/zip.go
apps/platform/pkg/fileadapt/localfiles/localfiles.go

Changes behavior from ignoring all dotfiles (files that start with `.`) to not ignoring.  There are certain meta data types that allow files that start with `.` (e.g., Files).  If a file gets zipped and is invalid for a given metadata type, server side validation when processing the zip should detect and fail the operation.
No current tests for any portions of the CLI in this area so manually tested to ensure that files that start with `.` are zipped and sent to server and changes reflected.
Resolves #4400

fix: do not ignore dotfiles when zipping local files

---

apps/cli/pkg/zip/zip.go

Switches from `filepath.Walk` to `filepath.WalkDir` to improve performance of zipping files.
This is an intermediate solution as the final solution should migrate to using [fs.WalkDir](https://pkg.go.dev/io/fs#example-WalkDir) to improve testability.  Making the change to `fs.WalkDir` requires a more invasive set of changes so for now, just picking up perf improvements of `filepath.WalkDir` vs. `filepath.Walk`.  Migrating to `fs.WalkDir` should be completed as part of a larger effort required to improve overall testability of the codebase.
No current tests so manual deploy performed via CLI.

chore: improve performance of zipping files

---

cypress/support/commands.ts
libs/apps/uesio/studio/bundle/views/collection.yaml

Displays the collection field name instead of the label in the first column of tables within the collection view.
Manual testing of Web UI.
Closes #4418

feat: display column name in studio collection view

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/viewinfopanel/viewinfopanel.tsx
libs/apps/uesio/io/bundle/components/dialog.yaml

There are a number of issues with Panels as described in #4392.
This PR helps to address one of them by adding an empty `actions` area to the dialog by default.  This was done for two reasons:
1. The component index is not currently visible for panels so there is no way for a user to know that an `actions` area even exists.  By having it exist by default, when dropping components on the dialog canvas, the footer/actions area will highlight so they will see that its there and a valid dropzone.  If the user does not want the area, they can remove it from yaml but this at least gives a visual indication that there is a footer/actions area until the component index problem is resolved.
2. Having the area by default seems like a more reasonable default since it's probably more common then not …

fix: add footer/actions area to dialog by default

---

libs/apps/uesio/core/bundle/bots/generator/init/bot.js
libs/apps/uesio/core/bundle/bots/generator/init/templates/template.package.json

Fix package.json name value
All tests pass and confirmed a new app/clone name has a leading `@` in the package.json name value.
Resolves #4421

fix: generated package.json name format

---

libs/ui/src/bands/user/operations.ts

Previously, we were using a route name as a path. This will only work in the special case where route name === route path.
Since we can now just navigate by route, we do that instead to fix the bug.
FUTURE IMPROVEMENTS:
Allow LoginResponses to include paramters and send those into the `navigateToRoute` function.

Fix home route redirects after login

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/propertysection.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/propertiesform.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/propforminternal.tsx

Adds support for any property to be included on the Styles section.
@humandad - I don't see any existing tests around this, am I overlooking any that exist?
Couldn't find any existing tests (likely should be added if they don't exist) so manual testing performed via Builder UI.
Resolves #4429

feat: support custom properties on styles section

---

apps/cli/pkg/cmd/workspace.go
apps/cli/pkg/command/workspace/deploy.go
apps/cli/pkg/command/workspace/retrieve.go

As described in #4393, there are some issues when using the `-d` flag with `retrieve` & `deploy`.  Upon review, a couple of things stand-out:
1. The existing logic of `retrieve` and `deploy` look for a `bundle/bundle.yaml` file and do not respect `-d` when doing so which is what leads to the errors mentioned in #4393.  
2. All other commands (except `app clone`) operate on cwd and do not offer a `-d` flag
Given the way that all commands current operate (except `app clone`) expecting there to be a `./bundle/bundle.yaml`, the options are to modify all commands to have a `-d` and then locate `bundle.yaml` appropriately or remove `-d` from `retrieve` & `deploy` to make them consistent with the way all the other commands behave.
For now, eliminating `-d` from `retrieve` and `deploy` so that …

fix: remove "dir" flag from retrieve & deploy commands

---

apps/platform/pkg/meta/component.go
apps/platform/pkg/meta/component_test.go

Ensure `defaultVariant` component prop is honored in builder.
The issue was that `defaultVariant` was not serialized in Component but was being serialized in RuntimeComponent.  Refactored to use common method for shared props.
All tests pass and builder now honors `defaultVariant`
Resolves #4434

fix: support defaultVariant component prop in builder

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dialogplain/dialogplain.tsx

Updating to `@floating-ui/react@0.27.3` in PR #4449 exposed an issue with the way that dismissing a dialog was being handled.  In v0.27.3, new functionality was added to [referencePress](https://github.com/floating-ui/floating-ui/releases/tag/%40floating-ui%2Freact%400.27.0) to handle native clicks.  This meant that click events would be processed and close the dialog when not intended.  For example, when clicking anywhere within the dialog "whitespace", on a "select" field, etc.
This behavior was reproduceable with v0.26.8 if the [e.stopPropogation()](https://github.com/ues-io/uesio/compare/fix/dialog-dismiss-handling?expand=1#diff-f433cef287b5d099ddc5915d2009b888830aa517f6984d6a630255fabbed99d2L81) was removed since essentially stopping propagation was solving the underlying issues with …

fix: dialog dismiss handling

---

libs/apps/uesio/builder/bundle/components/buildbar.yaml
libs/apps/uesio/tests/hurl_specs/component_dependencies.hurl

1. Fixes a lint issue with the buildbar component.
2. Adds the default avatar component variant as a dependency to the buildbar, so the profile indicator works on initial load in preview mode.
3. Fixes the annoying `component_dependencies.hurl` test. (This should be addressed in a future PR. Since we're in workspace mode we need to pull in some builder dependencies. Previously we did not need any because preview mode had no UI.)

Fixes some small issues left over from the new builder ui pr

---

libs/ui/src/bands/route/operations.ts

This PR removes some code that is no longer necessary and was causing an eslint warning. I ran the unit tests that would use JSDom and the pass just fine without this code. Improvements in dependencies may have made this no longer necessary.

Fix eslint unexpected use of self

---

package-lock.json
package.json

1. update `eslint-plugin-cypress` to v4.1
2. update misc minor

chore: update deps eslint-plugin-cypress major and misc minor

---

libs/apps/uesio/builder/bundle/components/mainwrapper.yaml

Fixes an issue where appkit variants were not getting loaded into the builder

Fix component panel dependency issue

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/stateapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dialogplain/dialogplain.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/panelwrapper/panelwrapper.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/sidepanelplain/sidepanelplain.tsx
libs/apps/uesio/io/bundle/componentvariants/uesio/io/sidepanel/base.yaml

1. Consolidates most of the floating-ui code for both `dialog` and `sidepanel` code into a single `panelwrapper` utility.
2. Keeps panels inside of the canvas in build mode.
3. Outside Press only dismisses the panel if the click is in the canvas, not in the builder toolbar area.

improve panel build experience

---

apps/platform/pkg/bundle/bundles.go
apps/platform/pkg/bundlestore/filebundlestore/filebundlestore.go
apps/platform/pkg/controller/route.go
apps/platform/pkg/preload/mergetypes.go

1. Improves error messages coming from bundlestore loads.
2. Enter a version context when displaying an Error route so that we're sure to have access to all error route dependencies.
3. Prevent panic when rendering the index template with nil dependencies.
4. Actually handle errors when getting metadata for the standard error routes.

Improve route error handling

---

libs/ui/jest-test-setup.js
libs/ui/jest.config.js

Just an idea for suppressing the window.scrollTo warnings in jest.
Based on this stackoverflow post.
https://stackoverflow.com/a/57312218
@techfg feel free to merge if you like this idea or close.
Thanks!

Suppress window scrollTo warnings

---

apps/platform-integration-tests/generated/@types/@uesio/package.json
apps/platform-integration-tests/tsconfig.json
libs/apps/uesio/core/bundle/bots/generator/init/templates/template.tsconfig.json
libs/ui/build.sh
libs/ui/src/public_types/client/package.json
tsconfig.base.json

1. Removes `package.json` from `generated` types folders as its unnecessary.  The contents of the folder is not a package and the types in the files within the folder are included via tsconfig references (e.g., `paths` and/or `include`)
2. Removes specifying `typeRoots` conforming to above
Tested generating an app with bots & component packs and all types are properly resolved.  ci & e2e will cover everything else.

chore: clean-up public types

---

libs/ui/jest-test-setup.js
libs/ui/jest.config.js
libs/ui/src/bands/route/operations.ts

The actual root dom element of of uesio pages is the element with the "root" id. We need to scroll that element to the top, since it's inside the body tag and overflow auto and h-screen, it acts as the viewport. This also lets us delete the special setup file we needed for jest to handle the `window.scrollTo()` call.
Navigate to a route and then scroll down. Then navigate to another route. That route should start scrolled all the way to the top.

fix scrolling on navigate

---

.github/workflows/master_branch_build.yaml

With nx projects now having correct dependencies and nx affected able to limit what is built during "lint/test/build" phase, some projects may not be built yet.  However, in order to build the docker image we need everything built so this PR will ensure that any projects that weren't affected are built prior to docker image creation.

chore: ensure all projects are built prior to creating image

---

.github/workflows/ci.yaml

update workflow paths-ignore
Manual testing of PR to ensure WF does not trigger in expected scenarios.

chore: update ci workflow paths-ignore

---

.github/workflows/ci.yaml
apps/platform/Dockerfile
apps/platform/pkg/cmd/serve.go
nx.json
scripts/tests-setup.sh

Consolidates the previous "Non-master branch build" and "Master/Release Branch Build" workflows in to a "CI" workflow. 
The new workflow will occur as follows:
1. PRs - lint, unit tests, build, typecheck, integration tests, e2e tests
2. Main Push - all the above plus deploy latest image to dev environment
1. Single ci.yaml file that covers all required steps/tasks - this can be split out to separate files if needed/desired
2. Only pushes to ECR after all checks (unit tests, e2e, integration, etc.) have passed
3. Fixes issue that would have resulted in not building a new image during the workflow when one should have been (due to checking for existence of the image in ECR by sha only)
4. Ensures that building images locally (when GITSHA is not defined) will update image named with GITSHA …

chore: update ci workflow for docker & int/e2e tests

---

apps/platform-integration-tests/bundle/bots/listener/tester_createlogin/bot.ts
apps/platform-integration-tests/bundle/bots/listener/tester_resetpassword/bot.ts
apps/platform-integration-tests/hurl_specs/listener_bot_create_site.hurl
apps/platform/pkg/auth/platform/platform.go
apps/platform/pkg/bot/jsdialect/generatorbot.go

Ensures that `password` is correctly detected and handled when creating a site.
Added integration tests to cover.

fix: handle password param in createsite

---

.github/workflows/ci.yaml
apps/platform/Dockerfile
apps/platform/pkg/auth/platform/platform.go

Cache docker dependencies when building image and also across CI workflow runs.
Local docker build times decreased significantly.  As an example, making a change in apps/platform and re-running `tests-ci` would take 35-40 secs to rebuild the image and it now takes < 10 seconds.
Instrumented github workflows to do the "cache dance" across CI runs which should result in the same benefit in our CI builds as well.
All tests pass locally, ci & e2e will verify rest.

chore: cache docker deps

---

.github/workflows/ci.yaml
README.md
scripts/get-hurl-version.sh
scripts/run-integration-tests.sh
scripts/tests-cleanup.sh
scripts/tests-init.sh

Hurl was recently updated to v6 and seems to work properly when npm version is used.  Eliminate separate apt install of hurl and use npm dep version.
All pass locally, ci & e2e will cover.

chore: use hurl from npm

---

.github/workflows/ci.yaml

The default run-name for workflows is the commit message, however for workflow_dispatch events (manual runs), there is no commit message.  
This PR will apply a name that includes the sha of the commit to the message when event is workflow_dispatch.
ci, e2e and manual runs will confirm.

chore: apply run-name to CI build on workflow_dispatch event

---

.github/workflows/ci.yaml

Reduces maintenance points by using `.nvmrc` for node version in workflows.
Note that if/when move to matrix build/test, this will have to change but for now, reduces the number of places we need to change things when we change to different version.  This is similar to recent change of using `go.work` to detect the go version instead of hardcoding the version in the CI workflow.

use .nvmrc for node version in workflows

---

.github/workflows/cleanup-cache.yaml

GH will automatically purge cache when its full, however no need to keep artifacts around that are (likely) no longer needed.
This workflow will:
1. Purge any cached item that hasn't been accessed in 5 days
2. Purge any cached item from closed PRs
the workflow itself will be the test.

chore: add cleanup-cache workflow

---

.github/workflows/cleanup-cache.yaml

Use gh cli instead of custom action to delete PR cached items.

chore: use gh cli to delete cached PR items

---

.github/workflows/cleanup-cache.yaml

Default token permission is READ so need to explicitly request permission to delete cached items.
workflow itself will test.

chore: needs permission to delete cache items

---

.github/workflows/ci.yaml

Splits lint/test/build/typecheck in to separate jobs in CI workflow to improve overall performance.
Reduces total time by ~45secs - now under 4 mins for full CI build (not including `update-dev-branch` job which only runs on push/workflow_dispatch to main).  Prior to this and other recent changes, full CI would take ~6-8mins.
build: build & test
check: format & lint
typecheck: typecheck

chore: split lint/test/build/typecheck in to separate jobs

---

apps/cli/go.mod
apps/platform/go.mod
apps/platform/go.sum
go.work

chore: update to go 1.23.5

---

.github/workflows/ci.yaml

After splitting out the CI jobs (build/check/typecheck), the build times increased by ~30-45secs.  
The reason for this is that the build & check steps each use go and rely on the default caching of go dependencies from `actions/setup-go`.  Unfortunately, the action does not contemplate that multiple jobs may result in different modules being downloaded (e.g., build will get everything but fmt only obtains a portion of the modules) and if the inputs are the same (which they are) across jobs, the first job to "save the cache" will win.  In our case, the `check` job finishes first so the cache only contains the modules of what was required for `go fmt`.  This results in `go build` needing to download modules every time since some modules aren't in the cache.
Unfortunately, …

chore: separate go cache per job

---

.github/workflows/ci.yaml

Eliminate the `runner.os` in the differentiators for go cache key since the default behavior of `actions/setup-go` already contemplates it as a differentiator in the cache key it builds.

chore: simplfy go cache key resolution

---

libs/apps/uesio/studio/bundle/permissionsets/standard.yaml

Temporary solution for #4554 
Able to create & view jobs locally, ci & e2e will cover rest.

fix: read perms to bulkjob/bulkbatch for studio standard profile

---

apps/cli/pkg/cmd/workspace.go
apps/cli/pkg/command/workspace/retrieve.go
apps/platform/pkg/meta/bot.go
apps/platform/pkg/meta/botcollection.go

Adds an option to `uesio retrieve` to only retrieve app specific type definitions.
`uesio retrieve --onlyTypes`

Add retrieve types only command

---

.prettierignore
libs/apps/uesio/appkit/bundle/files/emailtemplates/templates/confirmemail.html
libs/apps/uesio/appkit/bundle/files/emailtemplates/templates/createlogin.html
libs/apps/uesio/appkit/bundle/files/emailtemplates/templates/resetpassword.html

This PR fixes the truncated emails in Outlook Desktop.  It does not address the display/formatting issues generally in Outlook desktop or other email clients (e.g., dark mode, formatting, etc.) covered in #4558.
 
Resolves #4557
Tested all three email templates locally and all render with full text and all integration & e2e tests pass.

fix: email template "if mso" conditional statement format

---

.github/workflows/release.yaml

Migrate upload release artifacts action & enable workflow_dispatch in release workflow.

chore: change upload release artifacts action

---

.github/workflows/release.yaml

Only tag GHCR image with "latest" when tag is v#.#.# - for example, do not tag it "latest" when its a pre-release or manual workflow.

chore: restrict latest tag to v#.#.# tags only

---

libs/apps/uesio/appkit/bundle/components/note.yaml
libs/apps/uesio/appkit/bundle/views/login.yaml
libs/apps/uesio/studio/bundle/components/section_app_access.yaml
libs/apps/uesio/studio/bundle/components/section_app_icon_color.yaml
libs/apps/uesio/studio/bundle/components/section_app_name_desc.yaml
libs/apps/uesio/studio/bundle/components/section_app_owner.yaml
libs/apps/uesio/studio/bundle/views/admin.yaml
libs/apps/uesio/studio/bundle/views/app_new.yaml
libs/apps/uesio/studio/bundle/views/apppublish.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml
libs/apps/uesio/studio/bundle/views/login.yaml
libs/apps/uesio/studio/bundle/views/signup.yaml
libs/apps/uesio/studio/bundle/views/signuplanding.yaml
libs/apps/uesio/studio/bundle/views/site_new.yaml
libs/apps/uesio/studio/bundle/views/user.yaml
libs/apps/uesio/studio/bundle/views/workspace_new.yaml

Adds a declarative component to appkit called `uesio/appkit.note`. We'll use this throughout the studio to add helpful notes.
In a subsequent PR, I'll add the ability to add a title to the note and to make it collapsible.

use new appkit note component

---

libs/ui/src/context/merge.spec.ts
libs/ui/src/context/merge.ts

We have an `$If{}` merge that accepts a three-part value. First a condition, and then an if_true_merge and finally, and if_false_merge.
Since we merge into template strings in multiple stages, merges in the condition could result in the string "false". These conditions should still trigger the "false" condition, not the "true" condition.
Example Merge:
`$If{[$Prop{collapsed}][trueValue][falseValue]}`
If `$Prop{collapsed}` resolves to the string "false" we want the falseValue to be the final result of the if merge.

Treat if merge with false string as false

---

libs/apps/uesio/appkit/bundle/components/layout_detail_split.yaml
libs/apps/uesio/appkit/bundle/components/note.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/components/accordion/accordion.tsx
libs/apps/uesio/studio/bundle/views/app.yaml
libs/apps/uesio/studio/bundle/views/homecontent.yaml

Makes the appkit note component have the `collapsible` option.

Make appkit note component collapsible

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/collectionfieldpicker/collectionfieldpicker.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/iconprop/iconprop.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/popoutpanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/tablecolumns.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/fieldsproperties.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/stylesproperty/stylesproperty.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/propnodetag/propnodetag.tsx

Fixes the icon property styling in the builder.

Fix icon prop styling in builder

---

.github/workflows/ci.yaml
apps/platform-e2e/cypress.config.ts

Ensures nx graph can be built without requiring that either `UESIO_DEV` or `UESIO_AUTOMATION_PASSWORD` is present in environment.
Did not see much of (any) reason to not default to just using Mock credentials if automation password is not supplied.  If the server is not configured to support mock auth, the tests will fail anyway.  Seems more appropriate to use mock by default unless overridden via automation environment variable values.
Resolves #4579

chore: modify detection of credentials to use for cypress tests

---

scripts/tests/setup-docker.sh

Only `build-all` when we need to builder docker image during test script execution.

chore: only build projects when buliding docker image

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/buildwrapper/buildwrapper.tsx
libs/ui/src/component/component.tsx
libs/ui/src/styles/styles.ts

This PR no longer merges styleToken definitions into the component's definition when the component is processed. (If the component is a React component. Now, `styles.useStyleTokens` works in a similar way to `styles.useUtilityStyleTokens` in that it pulls in the variant definition and merges it in as needed. This way when working with components, you can pass down styleTokens definitions to other components and know that you only have the explicitly declared styleTokens, not the ones merge in from the variant.

Defer styletoken merging

---

libs/apps/uesio/appkit/bundle/components/note.yaml
libs/apps/uesio/sitekit/bundle/components/feature.yaml
libs/apps/uesio/sitekit/bundle/components/header.yaml
libs/apps/uesio/sitekit/bundle/components/hero.yaml
libs/apps/uesio/sitekit/bundle/components/section_hero.yaml
libs/apps/uesio/sitekit/bundle/components/section_split.yaml
libs/apps/uesio/sitekit/bundle/components/testimonial.yaml
libs/apps/uesio/studio/bundle/components/layout_note_form.yaml
libs/ui/src/component/display.spec.ts
libs/ui/src/component/display.ts

Adds a `hasSlotValue` condition that handles displaying a node or not depending on whether a slot value was provided.

Add has slot value display conditio

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/iconprop/iconprop.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/codepanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexcomponent.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexpanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/indexslot.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/propertieswrapper.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/fieldsproperties.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/searcharea.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/autocompletefield/autocompletefield.tsx
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/button/panelactionbutton.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/customselectfield/propfield.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/field/propfield.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/selectfield/propfield.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/tablabels/mainsection.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/tile/indextag.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/tile/propnodetag.yaml
libs/apps/uesio/builder/bundle/componentvariants/uesio/io/titlebar/primary.yaml
libs/apps/uesio/builder/bundle/themes/default.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/components/menu/menu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/listmenu/listmenu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/tooltip/tooltip.tsx

Cleans up some builder styling issues, and switches back to a more traditional "light mode". We can work on a dark mode at a later date, but this was causing problems for some issues with users who needed higher contrast.

builder styling cleanup light mode

---

apps/platform/platform/index.gohtml
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_header.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_tools.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/autocompletefield/autocompletefield.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/menu/menu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/listmenu/listmenu.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/tooltip/tooltip.tsx
libs/apps/uesio/io/bundle/fonts/roboto/font.css
libs/ui/src/styles/styles.ts
libs/ui/src/utilities/route.tsx

1. Adds back a font hack for safari.
2. Fixes a regression in menus and customselects.

Fix regression with fonts in safari and menus

---

package-lock.json
package.json

Updates `sonner` major to 2.0.1
Manual testing appears to work as expected.

chore: update sonner major to 2.0.1

---

README.md

Adds links to `nx` issues that track outdated dependencies in `nx` that limit ability to update `uesio` deps.
Doc update, no testing.

chore: add nx issue links to npm deps issue tracker

---

README.md

Update readme regarding pinning monaco-editor to 0.50.0.
Doc change only.

chore: update readme re: monaco-editor issue

---

libs/apps/uesio/io/bundle/components/field.yaml
libs/apps/uesio/io/bundle/components/group.yaml
libs/apps/uesio/io/bundle/components/iconlabel.yaml
libs/apps/uesio/io/bundle/components/link.yaml
libs/apps/uesio/io/bundle/components/markdown.yaml
libs/apps/uesio/io/bundle/components/metric.yaml
libs/apps/uesio/io/bundle/components/scrollpanel.yaml
libs/apps/uesio/io/bundle/components/searchbox.yaml
libs/apps/uesio/io/bundle/components/tablabels.yaml
libs/apps/uesio/io/bundle/components/table.yaml
libs/apps/uesio/io/bundle/components/tile.yaml
libs/apps/uesio/io/bundle/components/titlebar.yaml
libs/ui/src/component/component.tsx
libs/ui/src/context/context.ts
libs/ui/src/styles/styles.ts

Eliminates the "magic string" for default variants for components as mentioned in #4433.
Resolves #4433
Manual testing combined with e2e & ci.

fix: eliminate default variant magic string

---

apps/platform-integration-tests/generated/@types/@uesio/index.d.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/tablecolumns.tsx
libs/ui/src/public_types/server/index.d.ts

Fix eslint warnings that surfaced after recent npm minor deps bumps (e.g., typescript, eslint-plugin-react-hooks).
1. SaveOptionsApi defined but never used warning - does not seem to be used anywhere so removed 
2. hook warning on while loop - https://github.com/facebook/react/pull/31720 resolved in eslint-plugin-react-hooks 5.2.0

chore: fix eslint warnings

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/utilities/adjustableheightarea/adjustableheightarea.tsx

Uses AbortController instead of removeEventListener.

Use abort controller in adjustable height area

---

libs/ui/src/component/component.tsx

Fixes typescript types on `DeclarativeComponent` and `Component`

chore: fix uc types

---

libs/apps/uesio/studio/bundle/views/workspace_new.yaml

Fixes HTTP 500 that was generating the server side error `No metadata provided for field: uesio/studio.clonefrombundle in collection: workspace` when attempting to create a workspace that was cloned from an existing bundle.
Based on the history of workspace_new.yaml, it's not 100% clear how the clone from feature worked previously (if ever??).  What was occurring is that when view only fields are [removed](https://github.com/ues-io/uesio/blob/main/libs/ui/src/bands/wire/operations/save.ts#L16) from "changes" prior to sending to server, the [viewOnlyMetadata.fields](https://github.com/ues-io/uesio/blob/main/libs/ui/src/bands/wire/operations/save.ts#L20) contained an entry for `clonefrombundle` but the key in the [change](https://github.com/ues-io/uesio/blob/main/libs/ui/src/bands/wire/opera …

fix: clone workspace from bundle failure

---

apps/cli/go.mod
apps/platform/Dockerfile
apps/platform/go.mod
go.work

chore: update go 1.24.1

---

apps/cli/pkg/cmd/app.go
apps/cli/pkg/cmd/bundle.go
apps/cli/pkg/cmd/generate.go
apps/cli/pkg/cmd/login.go
apps/cli/pkg/cmd/logout.go
apps/cli/pkg/cmd/pack.go
apps/cli/pkg/cmd/root.go
apps/cli/pkg/cmd/sethost.go
apps/cli/pkg/cmd/site.go
apps/cli/pkg/cmd/siteadmin.go
apps/cli/pkg/cmd/status.go
apps/cli/pkg/cmd/upsert.go
apps/cli/pkg/cmd/work.go
apps/cli/pkg/cmd/workspace.go
apps/cli/uesio.go
apps/platform/main.go
apps/platform/pkg/cmd/migrate.go
apps/platform/pkg/cmd/root.go
apps/platform/pkg/cmd/seed.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/cmd/worker.go

Ensures that a non-zero exit code is returned from cli & platform when a failure occurs.
Previous code had a few different approaches with only some of them returning non-zero, in most cases, a zero exit code was returned even in failure cases.
This PR focuses on unifying the way the commands handle errors, bubbling them up to `main` and exiting with a 0 (success) or 1 (failure).  
There is still more work to be done on improving the cli & platform:
1. Reduce boilerlate code across commands
2. Improve logging (e.g., use slog in cli)
3. Several situations where functions return empty strings instead of what should be errors
4. etc

chore: return non-zero exit code in cli & platform on failure

---

libs/apps/uesio/appkit/bundle/components/form_detail.yaml
libs/apps/uesio/studio/bundle/collections/file.yaml
libs/apps/uesio/studio/bundle/views/file.yaml

Switches to using the more standardized appkit form detail component for the file detail page. (we should switch other detail pages to use this as well)

chore: use appkit detail form for the file detail page

---

libs/ui/src/component/component.spec.tsx
libs/ui/src/component/component.tsx

This fixes our implementation of defaultValues for props and defaultContent for slots. Before we were spreading the defaults before the definition. Now we spread them after the definition.
This fixes the case where the definition could have included an explicit undefined value like
```
{
myprop: undefined
}
```
Although a default would be generated for this property, the spread operation would actually override it back to the undefined value.
Added a failing test for this case.

Fix: Defaults should override explicit undefined definition

---

apps/platform-integration-tests/bundle/views/animals_queue_view.yaml
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/propertiesform.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dynamicform/dynamicform.tsx
libs/ui/src/component/display.ts
libs/ui/src/components/view.tsx
libs/ui/src/definition/definition.ts
libs/ui/src/hooks/componentapi.ts

Removes a backwards-compat hack we put in a while ago to support the Morandi app. I just went through the morandi app and fixed all this, so I think we can go ahead and remove the hack.
We no longer support the `id` property on uesio components. You have to use `uesio.id` to provide the id.

Remove id prop from base definition

---

apps/platform-integration-tests/generated/@types/@uesio/index.d.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/tablecolumns.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/conditionsproperties.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/propertiespanel/wire/wireproperties.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/paramsfield/paramsfield.tsx
libs/apps/uesio/io/bundle/componentpacks/chart/src/shared/definitions.ts
libs/apps/uesio/io/bundle/componentpacks/chart/src/utilities/chart/chart.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/accordion/accordion.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/box/box.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/dialog/dialog.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/field/field.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/grid/grid.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/griditem/griditem.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/table/table.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/components/tabs/tabs.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/tablabels/tablabels.tsx
libs/ui/src/component/component.spec.tsx
libs/ui/src/component/component.tsx
libs/ui/src/context/context.ts
libs/ui/src/context/merge.ts
libs/ui/src/definition/definition.ts
libs/ui/src/public_types/client/index.d.ts

Just some minor types improvements I did while attempting to fix something else.
1. Includes `DefinitionMap` with every `BaseDefinition`
2. Removes unnecessary type definitions.

Refactor: Base Definition Types Cleanup

---

libs/apps/uesio/appkit/bundle/componentvariants/uesio/appkit/item/actionable.yaml
libs/apps/uesio/studio/bundle/componentvariants/uesio/io/scrollpanel/sidebarinner.yaml
libs/apps/uesio/studio/bundle/views/homeleftnav.yaml

1. Removes some duplicated inline styling from the home sidebar.
2. Moves scrollbar to the edge of the container. (This is more apparent when scrollbars are always visible. The scrollbar is now all the way to the right with no padding.

Better scrollbars and variants for home sidebar

---

apps/cli/pkg/command/pack.go

Adds additional details on why we use AMD loader for monaco-editor.
comment only.

chore: add monaco-editor comment

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.gitignore
go.work
go.work.sum

Eliminate go.work.sum from git.  Reasons are:
1. go.work & go.work.sum are very poorly documented by go
2. go.work.sum seems to change frequently even when deps haven't changed - may be machine specific
3. both files are intended for development purposes only and not used in builds
For now, leaving go.work since uesio is monorepo with no publicly consumed libraries so having go.work does provide some benefits without each developer having to maintain it individually.  
If/When go.work & go.work.sum documentation is improved and there is clear information about these files and how to properly use them in various scenarios, this can be revisited.
See https://github.com/golang/go/issues/51941 & https://github.com/golang/go/issues/53502

chore: remove go.work.sum from git

---

libs/ui/src/component/component.spec.tsx
libs/ui/src/component/component.tsx

There are cases where a componentDef isn't correctly loaded into the registry, but the component still needs to be rendered. It makes sense that if a componentDef isn't loaded, then we have no idea what the default variant for a component is. However, if a component explicitly asks for a variant, and that variant is loaded, we should still respect that and merge the variant.
Previously we were bailing early if componentDef didn't exist in the registry.
This PR also adds tests to verify this functionality.

fix: variant merge bug and add tests

---

apps/platform/pkg/meta/filesource.go
apps/platform/pkg/meta/permissionset.go
apps/platform/pkg/meta/profile.go
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/datamanager/datamanager.tsx

1. Adds better error message logging to some metadata constructors. (This is now consistent across all metadata constructors)
2. Adjusts the `datamanager.tsx` to only load the fields that it's actually going to show. It was filtering out LONGTEXT fields in the table columns, but still loading them in the wire. This particular PR is intended to fix an issue with the following scenario:
1. View collection data for a workspace or site.
2. Select the `userfile` collection
3. Verify that the `uesio/core.data` field is NOT loaded.
This was causing performance issues and unnecessary file data downloads to occur when managing the `userfile` collection. (All of the actual file data was being downloaded)
Follow steps above and verify `uesio/core.data` is not loaded into the wire.

fix: data manager loads unnecessary fields

---

apps/cli/pkg/print/print.go

Fixes a panic when no session/user information is available when running `status` command.
Manual testing.

fix: cli status cmd panic when no session/user

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/defapi.ts

Small PR to add a `getContent` function to the builder API. This allows us to get the up-to-date contents of a metadata item in the builder. (We will use this for the implementation of the AI view-editor tool.

Feature: Add Get Content Builder API

---

libs/ui/src/bands/view/index.ts
libs/ui/src/components/view.tsx
libs/ui/src/utilities/route.tsx

The makeViewId function is called in the `route.tsx` component and the `view.tsx` component. This refactor improves the function such that the componentId is always merged with the current context and the default is`$root` if no componentId or path is sent in.

Refactor: Improve makeViewId function

---

libs/ui/src/bands/route/utils.ts

This is just a simple PR that names a function and pulls it out of the main area where it's used for clarity. In a followup PR I add some more functionality here. I also rename viewId to viewDefId to be more correct and explicit.
Eventually we'll need to do more checks in this function to verify that it was given a valid viewID.

Refactor: Add ViewDef Id parse function for clarity

---

apps/platform/pkg/datasource/fieldvalidations/metadataname.go
apps/platform/pkg/meta/bot.go
apps/platform/pkg/meta/metadata.go
apps/platform/pkg/meta/yamlnodeutils.go
libs/apps/uesio/studio/bundle/components/section_app_name_desc.yaml

Retricts metadataname to be lower case letter, digit or underscore (previously would allow a hypen `-`).
Closes #4720 
Manual testing confirms.

fix: do not allow `-` (hypen) in metadataname

---

apps/platform-integration-tests/generated/@types/@uesio/index.d.ts
libs/ui/src/public_types/server/index.d.ts

Adds missing `getHostUrl` func to ListenerBotApi type
types only, ci will cover.

fix: add missing getHostUrl to ListenerBotApi types

---

README.md

This reverts commit 2018cb6535b555a3da35c414e5be2fedb1daf41a.
Reverts readme update that was testing branch push policy.
doc only.

Revert "chore: test branc push policy"

---

libs/apps/uesio/core/bundle/bots/generator/init/templates/template.gitignore

Adds `.DS_Store` to generated `.gitignore`
Manual testing confirms its included :)

chore: include .DS_Store in default generated gitignore

---

apps/platform-integration-tests/bundle/integrations/oauth2_authorization_code_1.yaml
apps/platform-integration-tests/bundle/integrations/oauth2_authorization_code_2.yaml
apps/platform-integration-tests/bundle/integrations/secret_access_allowed.yaml
apps/platform-integration-tests/bundle/integrations/secret_access_forbidden.yaml
apps/platform-integration-tests/bundle/integrations/studio_apis.yaml
apps/platform-integration-tests/bundle/integrations/test_api_key.yaml
apps/platform-integration-tests/bundle/integrations/weather_api.yaml
apps/platform/pkg/bot/jsdialect/integrationmetadata.go
apps/platform/pkg/bot/jsdialect/loadbot.go
apps/platform/pkg/bot/jsdialect/runintegrationactionbot.go
apps/platform/pkg/bot/jsdialect/savebot.go
apps/platform/pkg/bot/systemdialect/systembot_load_external.go
apps/platform/pkg/bot/utils/mergeutils.go

Adds support for `$Site` merges on GetBaseURL to integration bots.  Previously, $Site was only supported in systemdialect bots.
Note - One other non-breaking change is that the previous code was intending to "hide/abstract" the `Integration` type from non-system dialects via IntegrationMetadata using a type declaration.  This was hiding/abstracting `Integration` but not the embedded types in `Integration` (e.g., BuitlIn, BundleBase, etc.).  This PR avoids type embedding for `IntegrationMetadata` ensuring that only what we want to expose is exposed.

feat: support integration site merges

---

apps/platform/pkg/bot/systemdialect/systembot_load_external.go

Removes the workaround for site collection loads that existed in studio now that #4576 has been implemented.  Note that #4576 does surface an error on the collection wire in the redux store but the error message itself is not surfaced to the page or component yet for display.
manual testing to ensure page loads when collections do not exist and that error message is in the redux store.

chore: remove collection load workaround

---

apps/cli/pkg/command/pack.go
libs/ui/build.mjs

Configures esbuild (used in cli `pack` command and in `ui/build.mjs`) to apply `react-jsx` transform.
With the recent changes to react 19, building esm format, etc. this is the next step in updating all the build configurations.  There is still some work to decide/update on tsconfig settings themselves but this change ensures we are using the recommended/most recent transforms for React code.
Manually tested including a custom component pack, ci & e2e will cover rest.

chore: use jsx automatic transform

---

apps/platform-integration-tests/hurl_fields/user.hurl
package-lock.json
package.json

Updates to hurl 6.1.1 and eliminates the workaround for https://github.com/Orange-OpenSource/hurl/issues/3869

chore: update to hurl 6.1.1

---

apps/platform/pkg/integ/bedrock/claude.go

Tool use messages in claude return an id property. It should be in our struct.

fix: add message id to claude messages

---

libs/ui/src/context/context.ts

1. lets `context.getSignalOutputData` take a generic type argument to return.
2. adds a new helper `context.getComponentDataValue`

feat: support generic arguments and new helper in context

---

libs/ui/src/context/context.ts

Fixes a bug where removeViewFrame worked incorrectly for `times > 1`.

fix: typo in removeViewFrame function

---

libs/apps/uesio/appkit/bundle/components/form_new.yaml
libs/apps/uesio/studio/bundle/views/app_new.yaml

Moves the "Create App/Start Over" buttons to the bottom of the "Create App" page.
This is a temporary solution as mentioned in #4695 to ensure that the user reviews all options in "Create App" prior to creating the app.  The overall UX of this page still needs to be improved via a "wizard" type component (or some other UX solution).
This is only meant to be temporary since it deviates from other pages that have buttons at the top.
Closes #4695 
Manual testing confirms expected behavior.

chore: move create app buttons to bottom of page

---

apps/platform-e2e/cypress/e2e/smoke.cy.ts
apps/platform-integration-tests/hurl_specs/allmetadata.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_siteadmin_context.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_version_context.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_workspace_context.hurl
apps/platform-integration-tests/hurl_specs/object_and_field_level_security_owner_field.hurl
apps/platform-integration-tests/hurl_specs/object_and_field_level_security_public_user.hurl
apps/platform-integration-tests/hurl_specs/site_signup.hurl
apps/platform-integration-tests/hurl_specs/view_definition_validation.hurl
scripts/tests/start-integration-tests.sh

Changes asserts in integration tests (and one e2e test) to be performed on explicit values instead of the value of a global variable.  There are a couple of reasons for this change:
1. When a change is made that affects a test that was using one of these variables, the variable would be updated but not the test so it is unclear what tests are affected by a specific code change.  Eliminating the variables ensures that when code changes that affects a test, the test itself is updated.
2. Reduce complexity when trying to run single test files directly via hurl (e.g., `npx hurl testfile.hurl`.  Previously, this was only possible by passing every variable in via the command line or having a variable file that contained all the necessary variables.  By eliminating the variables, the tests can …

chore: assert on explicit values in tests

---

apps/platform-e2e/cypress/e2e/builder.cy.ts
apps/platform-e2e/cypress/e2e/route_sanity.cy.ts
apps/platform-e2e/cypress/e2e/smoke.cy.ts

1. Marks `builder.cy.ts` e2e tests are skipped - See #4752
2. Improves handling of skipping tests - Previously, a test was conditionally executed when in CI that would log a message and then return from the entire test suite.  The challenge with this is that it shows a successful test but not the skipped test in the test summary so unless you were closely reviewing the detailed log output, you would not know that a test was skipped.  This PR changes that behavior to use the built-in methods that Mocha provides to skip tests.  This approach will mark tests as "pending" and they will have a blue color and appear in the test summary as pending.  This increases visibility to tests that are skipped.
Note - #4751 & #4752 should be investigated, resolved and these tests enabled in all …

chore: skip test improvements

---

apps/platform/Dockerfile
apps/platform/pkg/cache/redis.go
apps/platform/pkg/cmd/serve.go
docker-compose-local.yaml
docker-compose-tests.yaml
package.json

Ensures that docker containers honor environment variables.
This is the next step towards standardizing build/run/test/etc. to start from a "common" environment.  This is achieved via ensuring that `nx` runs all scripts/tasks as it will [automatically load]() environment files if present.
This PR ensures that any core `UESIO_*` environment variables (e.g., UESIO_USE_HTTPS, PORT, UESIO_PRIMARY_DOMAIN, etc.) are used when building the container (e.g., `npm run in-docker`, `npm run tests-docker`, etc.).
Notes:
1. there are still hardcoded `https` references in the code that require adjustment prior to everything working the way its intended using env variables as the starting point.  To ensure backwards compat until these are addressed, all env vars have defaults in docker compose files if …

chore: docker containers should honor environment variables

---

apps/platform-e2e/cypress/e2e/builder.cy.ts
apps/platform-e2e/cypress/e2e/route_sanity.cy.ts
apps/platform-e2e/cypress/e2e/smoke.cy.ts

Per #4751, enabling the e2e tests that are disabled in CI to see if they work.  All these tests pass locally.
Closes #4751.

chore: enable e2e tests in ci

---

apps/platform-integration-tests/hurl_specs/metadata_list_core_collections.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_siteadmin_context.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_version_context.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_workspace_context.hurl
apps/platform/pkg/bot/systemdialect/namespaceswap.go
apps/platform/pkg/bot/systemdialect/systembot_load_allmetadata.go
apps/platform/pkg/datasource/builtin.go
libs/apps/uesio/core/bundle/collections/agent.yaml

1. adds the `uesio/core.agent` collection. (This is different from the `uesio/studio.agent` collection.) It allows any site to access the agent metadata accessible to them.
2. Fixes a bug with the NamespaceSwap collection where builtin fields were getting swapped when they shouldn't be.
3. Handles queries on core metadata collections with a condition on `uesio/core.uniquekey`.

Feature: add core agent collection

---

apps/platform/pkg/bot/systemdialect/systembot_listener_addexternalbundle.go
apps/platform/pkg/configstore/environment/environment.go
docs/deployment/aws-ecs/taskdefinition-web-app.json
libs/apps/uesio/core/bundle/configvalues/bundle_store_domain.yaml
libs/apps/uesio/studio/bundle/bots/load/loadexternalbundlelisting/bot.ts
libs/apps/uesio/studio/bundle/bots/load/loadexternalbundleversion/bot.ts
libs/apps/uesio/studio/bundle/configvalues/external_bundle_store_base_url.yaml

1. Renames `bundle_store_domain` config value to `external_bundle_store_base_url`
2. Moves the config value to `studio` from `core` since it only makes sense and is only used in studio context
The current `bundle_store_domain` config value has a few shortcomings:
1. It required hardcoded `studio` prefix in the code to build the url
2. It required hardcoded `scheme` in the code to build the url
3. It was in `uesio.core` when it is only applicable to `uesio.studio`
Requires infra changes to dev & prod prior to deploy since environment variable is being renamed.
@humandad - I'm not setup to test this manually locally, can you run through a couple of tests?

chore: refactor external bundle store url config value

---

apps/platform-integration-tests/generated/@types/@uesio/index.d.ts
apps/platform/pkg/auth/samlauth/samlauth.go
apps/platform/pkg/bot/jsdialect/sessionapi.go
apps/platform/pkg/controller/oauth/authorize_metadata.go
apps/platform/pkg/controller/oauth/callback.go
apps/platform/pkg/datasource/domain.go
apps/platform/pkg/merge/merge.go
apps/platform/pkg/merge/merge_test.go
apps/platform/pkg/oauth2/authorizationcode_test.go
libs/apps/uesio/sitekit/bundle/bots/generator/view_footer/templates/footer.yaml
libs/apps/uesio/studio/bundle/bots/listener/select_plan/bot.ts
libs/ui/src/public_types/server/index.d.ts

Eliminates all hardcoded url scheme (e.g., `https`) references in the code and derives the scheme based on server settings.

chore: eliminate hardcoded https when url scheme is required

---

apps/platform/pkg/middleware/authenticate.go

When we're unable to obtain a user during authentication, if the browser session is nil, a panic occurs.
This panic masks the actual error that was encountered when attempting to create the user instance.  For example, if S3 AWS credentials are invalid, [GetUserFromBrowserSession](https://github.com/ues-io/uesio/blob/ebaf5b6bc64bfaacce7d8344a0d9dc7fe77a6ced/apps/platform/pkg/middleware/authenticate.go#L56) will return an error which will then try to remove a potentially `nil` browserSession.
Manual testing confirms that panic no longer occurs and underlying error is surfaced.

fix: server panics when unable to obtain user and there is no browser session

---

apps/platform-integration-tests/hurl_specs/bedrock_integration_actions.hurl
apps/platform/pkg/controller/integrationaction.go
apps/platform/pkg/integ/bedrock/bedrock.go
apps/platform/pkg/integ/bedrock/claude.go
apps/platform/pkg/integ/bedrock/invoke.go
apps/platform/pkg/integ/bedrock/stability.go
apps/platform/pkg/integ/bedrock/stream.go
apps/platform/pkg/integ/bedrock/uesiotest.go

1. Simplifies the interface for bedrock model handlers. The now just implement an "Invoke" and "Stream" method.
2. Adds a simple `uesio.test-simple-response` model and handler for testing. (The plan is to create another test model called `uesio.test-anthropic-response` that will respond in the anthropic format in a follow-up PR)
3. Removes some of our default input handling, since bedrock handles that input automatically anyways.
1. Test creating a new sitekit app with AI content and image generation.
2. Test creating a new appkit app with AI content.
4. Test adding fields to a collection on the collection detail page.
5. Test the CRM app AI tab to verify it still works.

Refactor: Better Bedrock interfaces for testing

---

apps/platform/pkg/creds/aws.go

Ensures that `UESIO_AWS_ENDPOINT` is applied to aws config when specified.
Note - There are several TODOs annoated.  This PR simply ensures that `UESIO_AWS_ENDPOINT` is always applied but there is some research to be done and decisions to be made on how we transpose third-party creds from UESIO_ to their respective configs since SDKs like AWS will use `AWS_*` variables automatically if present (if no explicit value are given) along with a few other items that need research and adjustment as determined.
Tested locally and all is good.

fix: ensure UESIO_AWS_ENDPOINT is used when specified

---

package.json

When using `nx exec`, if the target fails, the error output is incredibly verbose by default making it difficult to identify the actual error message/cause.
This PR migrates away from using `nx exec` and instead, defines root level nx targets in `package.json` which the npm scripts now call.  The `nx:run-commands` executor handles error output much more gracefully.
The net effect is zero essentially but in the case where errors occur, the error output has less noise.
tested manually.

chore: refactor root tasks to nx targets to improve error message output

---

libs/apps/uesio/aikit/bundle/componentpacks/main/src/components/agent_chat/agent_chat.tsx
libs/apps/uesio/aikit/bundle/components/agent_chat.yaml
libs/apps/uesio/aikit/bundle/permissionsets/agent_user.yaml
libs/apps/uesio/appkit/bundle/views/agent_thread.yaml
libs/apps/uesio/appkit/bundle/views/agent_threads.yaml
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/chatpanel.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/editortool.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx
libs/apps/uesio/studio/bundle/agents/viewbuilder/agent.yaml
libs/apps/uesio/studio/bundle/agents/viewbuilder/prompt.txt
libs/apps/uesio/studio/bundle/permissionsets/standard.yaml
libs/ui/src/definition/signal.ts
libs/ui/src/signalexports.ts

Adds an AI assistant chat panel to the builder.
NOTE: This is just a prototype. The assistant does not know about most of your app metadata. It can only take clues from what's already on the page, and the simple example in the system prompt.
This could be MASSIVELY improved by a better system prompt and bringing collection and component metadata into context.
The best use cases at the moment are
1. Adding/adjusting styles on existing components.
2. Changing existing properties or text.
At the moment, you will probably get the best results with an existing view, where the uesio view format can be inferred from that. I have not tested this with a brand new view, and will probably not work as well until we improve the system prompt and add in the available components and variants.

Adds an ai builder assistant

---

apps/cli/go.mod
apps/platform/Dockerfile
apps/platform/go.mod
go.work

chore: update go 1.24.2

---

.github/workflows/ci.yaml

The `main` branch is protected by rulesets that require status checks (e.g., build_and_test, format, lint), however the `ci` workflow has `paths-ignore` meaning that the workflow won't run if only certain files have changed.  The issue is that GH required status checks are still required but the workflow will never run. 
This PR works around this limitation in GH using the following approach:
1. Defines a `check_changes` job that checks which files have changed and sets an output variable `run_job` to true if any files outside of the `ignore` list have changed
2. Conditions all other jobs to only run when `run_job == true`
In this situation, the job will be skipped and the result will be "succeeded" thereby satisfying the required status check and allowing the ruleset to not require the …

chore: workaround for gh required status checks

---

.github/workflows/ci.yaml

Checks out code prior to running check-changes step.
ci will cover.

chore: check changes requires checkout

---

apps/platform/pkg/auth/platform/platform.go
apps/platform/pkg/auth/platform/platform_test.go
apps/platform/pkg/bot/jsdialect/generatorbot.go

1. Ensures that generated password during site creation meets requirements of password policy
2. handles generation errors that occur during password generation (validation of the password handling remains the same)
3. Properly enforces the special character requirement in the policy - previously it would accept anything that wasn't a digit/letter/underscore/hyphen as a valid special character (e.g., it would allow a ` ` (space)).
Resolves #4768 
Tested manually and added some password unit tests.

fix: ensure generated password meets requirements

---

apps/platform/pkg/controller/server.go
apps/platform/pkg/http/localhostclient.go

Decreases dns lookup timeout from the default of 30 seconds to 5 seconds.  This needs to be monitored and can be adjusted but 5 seconds should be more than adequate for most situations.
tested manually and confirmed the 5 second limit.

chore: decrease dns lookup timeout

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/signalsapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/signals/component.ts

Fixes an issue where signal properties were not being evaluated/incorporated properly when coming from yaml.
When choosing "Run a component signal" in the builder and then choosing the signal from the component, the following error would occur:
Steps to reproduce:
1. Create view
2. Add button
3. Choose Signals tab
4. Add new signal
5. Choose `Run Component Signal`
6. Select `Tabs`
7. Select `Select Tab` for `Component Signal`
Tested manually, signals are read and run when called.  ci & e2e will cover rest.

fix: signal properties is an array in yaml

---

apps/cli/project.json
apps/platform/project.json

go project format/vet/tidy tasks should be cacheable.
Tested manually.

chore: mark go format & lint tasks cacheable

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_tools.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/buildmode.ts
libs/ui/src/hooks/builderapi.ts

Fixes issue where toggling to "preview" mode in the builder was losing any "in-progress" changes.  This appears to be a regression that was introduced in the work recently completed on the new "builder bar".
Resolves #4816 
Manually tested all options in build bar and ensured that in-progress changes are maintained when toggling between "Preview/Build" modes.

fix: preview mode loses "in-progress" changes on view

---

apps/platform/pkg/bot/jsdialect/apihelpers.go
apps/platform/pkg/bot/jsdialect/generatorbot.go
apps/platform/pkg/bot/tsdialect/tsdialect.go

1. uses `buf.String()` instead of `string(buf.Bytes())`
This is part of a series of changes to get us inline with golangci-lint rules.

chore: convert buffer directly to string

---

apps/platform/pkg/auth/platform/platform.go

This issue was caught in a golangci-lint check for unused variables.
`loginmethod` was queried and never used until it was overwritten with another query. I can't think of any reason why we'd need to query this twice.

refactor: remove redundant loginmethod query

---

apps/platform-integration-tests/hurl_specs/collection_fields_lifecycle.hurl
apps/platform-integration-tests/hurl_specs/metadata_list_workspace_context.hurl
apps/platform/pkg/bot/systemdialect/systembot_after_collection.go
apps/platform/pkg/bot/systemdialect/systembot_after_integration_type.go

Ensures that workspace is respected when collection & integration type metadata is being deleted after a collection/integration type has been removed.
 
Resolves #4801 
tested manually and confirmed. 
TBD: Write tests.

fix: respect workspace in collection & integration type after save bots

---

apps/platform/pkg/adapt/postgresio/save.go

When updating a metadata item, the `createdat/createdby` fields were being updated.  In the case of individual metadata items, this had no net effect since we load oldvalues of the current item prior to updating so we updated createdby/at with its own old value.  However, in the case of a deploy, due to the orchestration of things, we insert & update some metadata types and in that case, we didn't have oldvalues when the update came around.  This resulted in the created fields getting zero'd out.
This PR eliminates updating createdat/by fields during `UPDATE` statements since we should not be doing it anyway.
Tested manually and confirmed expected behavior.

fix: do not update createdat/by on update

---

libs/apps/uesio/studio/bundle/fields/uesio/studio/workspace/agents.yaml

Ensures that agents & their userfiles are physically deleted from db & filesystem when workspace is deleted.
Manually tested and confirmed expected behavior.

fix: ensure agents are deleted when workspace gets deleted

---

libs/apps/uesio/builder/bundle/componentpacks/main/src/api/stateapi.ts
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_main_buttons.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/helpers/buildmode.ts

Fixes the issue where starting in preview mode and then toggling to build mode would result in portions of the builder not displaying properly (e.g., index, properties panel).
The changes made in https://github.com/ues-io/uesio/pull/4817 actually fixed multiple issues.  In the previous code, the detection of the namespaces component was always returning `false` so we were attempting to load deps every time we went to `build` mode.  ~~We should likely move the way we determine whether or not we need to load deps in to state vs. checking for a component that we know doesn't exist in "preview" mode but this PR will solve the issue for now.~~ UPDATE: Migrated to using state for builder dep detection.
Tested manually and all works.

fix: initial preview then toggle to build mode breaks builder

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/dynamictable/dynamictable.tsx
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/multipermissionpicker/multipermissionpicker.tsx
libs/ui/src/bands/wire/class.ts

1. Removes the ability to optionally send in a "recordid" during a `wire.createRecord` call. This option was only used in one place, and it encourages a hack. (storing actual record information in the "recordid")
NOTE: This is part of a larger effort to clean up and standardize the `wire.createRecord` function.
2. Adjusts and simplifies the `DynamicTable` component to receive an array of initialValues, instead of a map of values with their ids. (This component is currently only used in one place, so this adjustment could be made)
3. Changes the `multipermissionpicker` component to no longer rely on setting non-standard record ids in a wire.
TESTING:
All of the permissionset editing views in the studio should work the same as before.

Refactor: Remove recordid option from create record

---

apps/platform-e2e/cypress/support/testdata.ts
apps/platform-integration-tests/hurl_seeds/delete_app.hurl
apps/platform-integration-tests/hurl_specs/delete_api.hurl
apps/platform/pkg/adapt/postgresio/conditions.go
apps/platform/pkg/controller/collectiondeleteapi.go

1. Adds support for the following sql operators:
1. sw = STARTS_WITH (already supported in conditionsapi, only added to deleterecordapi)
2. cs = CONTAINS  (already supported in conditionsapi, only added to deleterecordapi)
2. Modified our e2e & integration tests to always create apps starting with the name "tests"
3. Modified our test cleanup code to delete all apps starting with "tests" name
4. Fixed a few issues with asserts on existing tests that were not correctly querying for data and/or retrieving files so they would never return any data (even if it was there) but were asserting on counts = 0.  If there is data, it will be retrieved now so the asserts will work as expected.
> [!IMPORTANT]
> There is some down side to adding support for these operators.  These operators are now …

feat: add additional sql operators

---

apps/platform-integration-tests/hurl_specs/builder_dependencies.hurl
apps/platform/pkg/routing/deps.go
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/buildbar/buildbar_tools.tsx
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/mainwrapper.tsx
libs/apps/uesio/studio/bundle/featureflags/chat_panel.yaml
libs/ui/src/bands/featureflag/index.ts
libs/ui/src/bands/selectlist/index.ts
libs/ui/src/component/display.ts
libs/ui/src/context/context.ts
libs/ui/src/definition/featureflag.ts

1. Removes unnecessary loading of all feature flags and language labels in the builder dependencies. (This isn't necessary, because this is done anyways for *every* page load whether or not you're in the builder. Doing this in the builder, was essentially loading these things twice.
2. Adds the `uesio/studio.chat_panel` feature flag.
3. Makes sure that the `uesio/studio.chat_panel` feature flag value is available in build mode.
4. Removes all `selectByName` selectors. (for feature flag and select list). This is a naive approach to getting values. You can't just ask for a value by name without the fully qualified key. How would you differentiate values from different namespaces?
5. To request a feature flag value, you now need to provide the fully qualified key. If you don't, it will use …

add chat panel feature flag

---

apps/platform/pkg/datasource/cascade.go

1. Simplifies the cascade delete logic.
Because of a previous implementation where multiple operations were handled by the cascade delete function, this code was more complicated than it needed to be. This PR removes an unnecessary for loop, and returns early for fields not relevant to CASCADE delete.

refactor: simplify cascade deletes

---

libs/apps/uesio/studio/bundle/permissionsets/standard.yaml
libs/apps/uesio/studio/bundle/routes/componentpack.yaml
libs/apps/uesio/studio/bundle/routes/componentpacks.yaml
libs/apps/uesio/studio/bundle/views/componentpack.yaml
libs/apps/uesio/studio/bundle/views/componentpacks.yaml
libs/apps/uesio/studio/bundle/views/workspacenav.yaml

This is just a start, but this PR adds a UI for administering component packs behind the `manage_components` feature flag. Right now, you can only add and delete component packs.
However, in a follow-up PR we could add the ability to browse files in a component pack and even make edits.

feat: add component pack metadata item to workspace ui

---

apps/platform/pkg/bot/jsdialect/apihelpers.go
apps/platform/pkg/bulk/exportfiles.go
apps/platform/pkg/bundlestore/filebundlestore/filebundlestore.go
apps/platform/pkg/bundlestore/workspacebundlestore/workspacebundlestore.go
apps/platform/pkg/controller/file/componentpack.go
apps/platform/pkg/controller/file/font.go
apps/platform/pkg/controller/file/serve_file.go
apps/platform/pkg/controller/file/userfile.go
apps/platform/pkg/fileadapt/s3/download.go
apps/platform/pkg/fileadapt/s3/list.go
apps/platform/pkg/filesource/download.go
apps/platform/pkg/filesource/upload.go
apps/platform/pkg/meta/userfilemetadata.go
apps/platform/pkg/types/file/filemetadata.go
apps/platform/pkg/types/file/localfilemetadata.go

1. Instead of creating a one-off wrapper for workspace file metadata, this PR just makes the `meta.UserFileMetadata` implement the `file.Metadata` interface.
2. Store and Pass `time.Time` as values instead of pointers. As suggested here... https://pkg.go.dev/time#Time
> Programs using times should typically store and pass them as values, not pointers. That is, time variables and struct fields should be of type [time.Time](https://pkg.go.dev/time#Time), not *time.Time.
NOTE: This change is needed for another change that will simplify managing files in the studio. (And allow for managing component pack files)

refactor: make userfilemetadata implement file.metadata

---

apps/platform/pkg/datasource/metadata.go
apps/platform/pkg/datasource/metadata_test.go

Removes the session argument from GetFieldMetadata
At one point we required the session to be passed into the GetFieldMetadata function. I think it may have been related to merging in labels at one point. However, I think we should handle this in a different way if we every do implement that functionality.

refactor: remove session argument from GetFieldMetadata

---

libs/apps/uesio/studio/bundle/componentpacks/main/src/components/multipermissionpicker/multipermissionpicker.tsx
libs/apps/uesio/studio/bundle/components/multipermissionpicker.yaml
libs/apps/uesio/studio/bundle/components/permissionmapeditor.yaml
libs/apps/uesio/studio/bundle/views/permissionset.yaml
libs/apps/uesio/studio/bundle/views/permissionsetcollection.yaml
libs/apps/uesio/studio/bundle/views/permissionsetintegration.yaml

Fixes a bug in the permission set editor where previous permissions were wiped out when a new permission checkbox was selected.
Resolves https://github.com/ues-io/uesio/issues/4868

fix: permission set editor bug

---

apps/platform/pkg/bundle/cache.go
apps/platform/pkg/bundlestore/filebundlestore/filebundlestore.go

We cache bundle file paths and individual bundle items, but we never implemented a cache for bundle definitions (the bundle.yaml file). This was causing a local file system / s3 load every time we went to get metadata.
This PR implements a cache for package bundle definitions.

feat: add bundledefs to bundle cache

---

apps/platform/pkg/cmd/serve.go
apps/platform/pkg/controller/file/componentpack.go

Allows any file within a component pack to be served.
Previously, serving files from within a componentpack was limited to the regex `[a-zA-Z0-9\\-_]+\\.(?:json|js|xml|txt|css){1}(?:\\.map)?}"` so in short, only files with a single `.` and were of the listed extensions could be served.  This limitations seems to be somewhat historical but presents issues when componentpacks need to contain other files that need to be served.  
There does not seem to be any reason for limiting the files served from a component pack (the component pack review process should vet and discover anything that it not appropriate) so in order to support all uses cases, any file inside of a componentpack can be served.
Additionally, the `Content-Disposition` header `filename` property will contain the actual …

feat: serve any componentpack file

---

apps/platform/pkg/bot/systemdialect/systembot_after_bundledependency.go

Errors in queries for adding licenses were not handled correctly. We now handle any errors, except for the record not found error. Previously, we expected that error, but were not handling any other errors that may arise from those queries.

fix bundle dependency error handling

---

README.md
apps/platform-e2e/project.json
apps/platform-integration-tests/project.json
apps/platform/project.json
apps/platform/scripts/dev.sh
apps/platform/scripts/wait-for-dev.sh
docker-compose.yaml
package.json
scripts/run-docker-tests.sh

Migrates to [continuous tasks](https://nx.dev/recipes/running-tasks/defining-task-pipeline#continuous-task-dependencies) which was introduced in [Nx 21](https://nx.dev/blog/nx-21-continuous-tasks).
1. All `tests-*` targets will now automatically start the `platform` dependencies (e.g., Postgres & Redis) along with the `platform` itself.  `npm run start` (which is just a proxy to `npm run dev`) and `npm run watch-dev` will also start dependencies in addition to the platform.  If the platform and/or its dependencies are already running, starting them will be "skipped" which allows you to manually start the server (e.g., `npm run start` or `npm run watch-dev` and then simply run `npm run tests-integration`, etc.) just like before.  In short, running any `test-*` target will ensure that …

chore: migrate to nx 21 continuous tasks

---

apps/cli/project.json

Adds go related files to CLI nx target inputs.
The CLI does not depend on the platform project, however it does depend on code in the platform project since the platform project is a "shared" library as currently architected.  Prior to this PR. if code in the platform project was modified that the CLI relied on, nx would not detect those changes as it relates to the CLI project and therefore would not re-run tasks and instead pull from cache.  Adding in go specific inputs from the platform project ensures that NX can properly detect when code that the CLI may use has changed.
Tested manual changes to go related files in the platform project and confirmed that the CLI re-executes it's tasks and do not pull from cache.  ci & e2e will cover rest.

chore: include platform go code in cli target inputs

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/uploadarea/uploadarea.tsx

Ensures that upload file triggers in all cases.  The prior implementation had two shortcomings:
1. After "deleting" the file, uploading the same file again would not trigger the upload
2. If the same "file name/path" is selected but the file itself is different, the upload would not trigger
The above issues are due to the fact that the browser won't trigger onChange when the "same file is detected" but it bases "same file" on name/path, not physical content.
Manual testing confirms uploads trigger in all cases.

fix: ensure upload file trigger in all cases

---

apps/platform/pkg/auth/cache.go

Uses the site name for user cache key instead of the site id.
A userid is unique to a site so technically, only it needs to be part of the cachekey since we cache for a given site.  However, having the site/app name info in the keys is helpful for troubleshooting.
When calling `getStudioSession` a "facade studio session" is created, however it does not have a value for `site ID` since that would require a lookup.  This is used for things like "seed" command.  
Ultimately, the way we handle facade/anon/admin sessions and construct them in certain situations needs to be revisited, however for now, not relying on the site.ID for the user cache key is OK since userid itself is what makes the key unique.
Tested locally and confirmed expected behavior.  ci & e2e will cover basics.

fix: use site name for user cache key instead of site id

---

apps/platform/seed/uesio/core.user.json
apps/platform/seed/uesio/studio.bundlelisting.json

Updates seed data to include the following:
1. Ben user is an admin
2. App Kit & Site Kit are registered as starter templates OOB
3. Add bundle titles to all bundles
Previously, after running `npm run migrations` and `npm run seeds`, step 1 & 2 above would have to be manually configured to be up and running locally.
Tested fresh install locally as well as updating a local existing copy and all worked as expected.

chore: update seeds to avoid manual config of starters and an admin user

---

libs/apps/uesio/appkit/bundle/components/form_detail.yaml

1. Ensures that after a save or cancel, the form mode is toggled back to read
2. Eliminates the "Read" button since it's technically a cancel button and cancel seems more intuitive language for a user
3. Ensure the cancel button appears whenever form is in EDIT mode
Tested manually and confirmed behaves as expected.

fix: toggle mode when save/cancel in form_detail

---

libs/apps/uesio/studio/bundle/routes/user.yaml

Change page title to use $Param{userid} instead of $Record{username} because the users wire is loaded asynchronously so the username isn't available when page title is generated and it was resulting in a page title of "User: ".
Not that there are two downsides to this approach and possibly could consider just using "Manage User" for the page title but having the userid in the title is helpful for site navigation:
1. If no {userid} is specified in the route, the page title will remain "User: "
2. If the {userid} is not valid, the page title will contain the user id even though technically it's not a page for that user since the user isn't valid
Side note - When an invalid user is specified, the page shows blank instead of serving a page not found 404 but that is a separate issue from this …

fix: page title on user view

---

libs/apps/uesio/appkit/bundle/components/section_delete.yaml
libs/apps/uesio/studio/bundle/views/user.yaml

Adds `editModeOnly` property to section_delete component so that it can be used in EDIT or READ situations.
Tested locally and confirmed expected behavior.

chore: refactor section_delete display conditions

---

libs/ui/src/component/component.spec.tsx
libs/ui/src/components/slot.tsx
libs/ui/src/context/merge.ts

This PR reverts some of the changes I made in February. https://github.com/ues-io/uesio/pull/4599
1. Pass the context of the creator of the slot as part of the slot definition so that it can be used when it's time to render.
2. For example, if the contents of a slot reference a wire in the same view, it should be available when that slot is rendered. Even if that slot is being rendered as part of a different view.
EXAMPLE:
```
- uesio/core.view:
view: uesio/cms.admin_nav
params:
selected: articles
slots:
crumbs:
- uesio/io.group:
uesio.variant: uesio/appkit.breadcrumbs
components:
- uesio/appkit.icontile:
tileVariant: uesio/appkit.breadcrumb
title: Articles
icon: article
signals:
- signal: route/NAVIGATE_TO_ASSIGNMENT
collection: uesio/cms.article
viewtype: list
- uesio/appkit.icontile: …
```

Fix slot context issues

---

apps/platform/pkg/bot/systemdialect/systembot_listener_runagent.go
apps/platform/pkg/integ/bedrock/bedrock.go
apps/platform/pkg/integ/bedrock/claude.go
apps/platform/pkg/integ/bedrock/invoke.go
apps/platform/pkg/integ/bedrock/stream.go
libs/apps/uesio/aikit/bundle/bots/listener/ai_chat/bot.ts
libs/apps/uesio/aikit/bundle/bots/listener/summarize_thread/bot.ts
libs/apps/uesio/aikit/bundle/componentpacks/main/src/components/agent_chat/agent_chat.tsx
libs/apps/uesio/aikit/bundle/componentpacks/main/src/utilities/claudebutton/claudebutton.tsx
libs/apps/uesio/appkit/bundle/bots/generator/collection/bot.js
libs/apps/uesio/appkit/bundle/bots/generator/collections/bot.js
libs/apps/uesio/appkit/bundle/bots/generator/sample_data_collection/bot.js
libs/apps/uesio/builder/bundle/componentpacks/main/src/components/mainwrapper/editortool.tsx
libs/apps/uesio/sitekit/bundle/bots/generator/starter/bot.js
libs/apps/uesio/studio/bundle/agents/viewbuilder/agent.yaml

1. Adds a default model to be used for bedrock when one isn't provided.
2. Uses the default model whenever possible in our calling code.
3. Removes special region handling for Claude 3.5 and switches to cross-region inference models.
Now, most of our AI features will use Claude 3.5 Haiku (Upgraded from Claude 3 Haiku). The builder agent will now use Claude 4 (Upgraded from Claude 3.5 v2).
1. Test creating fields for a collection
2. Test image generation models in sitekit.
3. Test the sitekit starter template.
4. Test the appkit starter template.
5. Test the view builder agent.
NOTE: I have not requested model access to these new models in the PROD AWS account, only DEV.

Update to latest models

---

apps/platform/pkg/bot/systemdialect/systembot_load_allmetadata.go
apps/platform/pkg/datasource/load_metadata.go
apps/platform/pkg/types/file/filemetadata.go
libs/apps/uesio/io/bundle/componentpacks/main/src/components/fileattachment/fileattachment.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/file/file.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/fileimage/fileimage.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/filevideo/filevideo.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/uploadarea/uploadarea.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/userfile/userfile.tsx
libs/apps/uesio/studio/bundle/views/file.yaml
libs/ui/src/context/merge.ts

This PR improves the File UI for working with Files Metadata in a workspace.
1. Switch to using the new `uesio/core.attachments` field instead of the hacked in `uesio/studio.attachments` field.
2. Prevent editing of "attachment" files. The should only be able to be created or deleted.
3. Allow creating additional file items in a "file set". (Previously you could only create one if no others existed.)
1. Go to the Files area of a workspace.
2. Create a new file.
3. Upload a file to the file. 🤦 
4. Upload another file to the file.
5. Delete a file.
6. Verify that you cannot edit existing attachments.
7. Go to your user profile in the studio by clicking the icon in the bottom left.
8. Change your profile picture. (Verifying that FILE fields still allow updating)

feat: Improve file ui in workspaces

---

libs/ui/src/context/context.ts
libs/ui/src/context/contextsignals.spec.ts
libs/ui/src/context/signals.ts

When trying to encapsulate wires and components into sub views, it is sometimes important for the subview to escape it's own context to run signals that were passed in as parameters.
This PR adds the `VIEW` type to `context/CLEAR` signal. If no viewDef is specified, it just removes the first VIEW context frame on the stack. If a viewDef is specified, it removes that particular view context. If a view with that particular viewDef is not found, nothing happens.

Feat: Add Signal to Clear View Context

---

apps/platform/pkg/controller/bundlesretrieve.go
apps/platform/pkg/controller/file/serve_file.go
apps/platform/pkg/controller/retrieve.go

Ensure `Content-Type` and `Content-Disposition` headers are set properly on bundle & app retrieve.
tested manually to ensure headers are set as expected.

fix: ensure retrieving bundle or app sets content-disposition header correctly

---

apps/platform/pkg/controller/file/serve_file.go
apps/platform/pkg/controller/file/userfile.go
apps/platform/pkg/middleware/http_caching.go

In cases where we were setting cache control header to 1 year, in cases where caching isn't enabled (e.g., dev mode) or we conditionally set the header, explictly set the header to not cache.
Note - There are several places in the code that do not set cache-control at all and there are shortcomings with the current values we use with cache-control.  This PR does not address those, only modifies current locations where we did set cache control headers to always set cache control headers (either to cache or not to cache).  See https://github.com/ues-io/uesio/issues/4993.
Manually verified cache-control headers are explicitly set to `no cache` in the cases were 1 year cache was conditionally applied.

chore: more explicit on cache-control headers

---

apps/platform/pkg/controller/favicon.go
apps/platform/pkg/controller/mergedata.go
apps/platform/pkg/meta/site.go
apps/platform/pkg/preload/mergetypes.go
apps/platform/platform/index.gohtml

Enables http caching for favicon.
Note - This only addresses the ability to support http caching for favicon.  See #4674 (which has been updated to account for the changes in this PR) for other issues related to favicon.
@humandad - When reviewing, please pay particular attention to https://github.com/ues-io/uesio/pull/4996/files#diff-dee56ef84e65aee0654893201db7dae31624d048d65c98e014031ee14fa1d7b9R15.  Previously, the code would `GetContextAppBundle` and `Favicon` from there, however this PR changes to always just use the current site (via `session.GetSite()`).  I believe the net result should be the same but would like to verify.
Tested manually and proper favicon url with `v=###` syntax is generated and cache headers set as expected.

chore: support http caching for favicon

---

libs/apps/uesio/appkit/bundle/components/tile_file.yaml
libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/grid/two_columns_large.yaml
libs/apps/uesio/appkit/bundle/permissionsets/public.yaml
libs/apps/uesio/appkit/bundle/views/file_attachments.yaml
libs/apps/uesio/io/bundle/components/card.yaml
libs/apps/uesio/io/bundle/componentvariants/uesio/io/filefield/default.yaml
libs/apps/uesio/studio/bundle/views/file.yaml

1. Abstracts file attachments for a record into a single subview component.
2. Uses this new view for the Files UI in Workspaces.
For the functionality of this PR to work, the following PRs must be merged.
https://github.com/ues-io/uesio/pull/4988
https://github.com/ues-io/uesio/pull/4987
https://github.com/ues-io/uesio/pull/4986
Try out the Files UI and verify that everything works as expected for both files from the local namespace, as well as files that are installed from a bundle.

feat: file attachments view

---

apps/platform/pkg/controller/bundleversionslist.go

1. Always return an array even when no items (instead of previous `null` response)
2. Perf improvement to avoid re-allocations when building response slice
Manually confirmed expected outcome, ci & e2e will cover rest.

fix: bundle versions list api improvements

---

libs/apps/uesio/appkit/bundle/componentvariants/uesio/io/button/itemaction.yaml
libs/ui/src/styles/styles.ts

In order to support cases where you only want to apply a style if the browser supports hovering, this PR adds a new variant called `has-hover`. Style tokens used with this variant will only apply if the browser has hover support.
1. Go to the files section of a workspace in the studio. Verify that the delete icon shows when you hover of a file tile.
2. Next turn on "responsive mode" in your browser's devtools. Verify that the delete icon always shows when viewing as a mobile device.

feat: add has hover variant

---

libs/apps/uesio/appkit/bundle/components/form_detail.yaml
libs/apps/uesio/core/bundle/bots/generator/agent/bot.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/list.tsx
libs/apps/uesio/studio/bundle/collections/label.yaml
libs/apps/uesio/studio/bundle/collections/translation.yaml
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/translations/translationitem.tsx
libs/apps/uesio/studio/bundle/views/label.yaml
libs/apps/uesio/studio/bundle/views/translation.yaml

1. For better consistency in detail pages, use the `uesio/appkit.form_detail` component.
2. Make list field respect field mode context.
3. Fixes some labels
View a translation and label detail page for a workspace.

refactor use form detail component for labels and translations

---

libs/apps/uesio/appkit/bundle/views/file_attachments.yaml
libs/apps/uesio/studio/bundle/componentpacks/main/src/components/recorddatamanager/recorddatamanager.tsx
libs/apps/uesio/studio/bundle/components/recorddatamanager.yaml
libs/apps/uesio/studio/bundle/views/recorddata.yaml
libs/ui/src/bands/collection/types.ts
libs/ui/src/collectionexports.ts
libs/ui/src/metadata/types.ts

1. Allows viewing, deleting, and creating attachments in the record data manager.
2. Improves the UX of the "Back to records list" button.
3. Adds and emptyState placeholder for record access tokens (instead of showing an empty table)
1. Visit the record data manager. 
2. Create/Delete/View File attachments
3. Use and Enjoy the new Back button.

refactor: add attachments to record manager

---

apps/platform/pkg/bundlestore/bundlestore.go
libs/ui/src/platform/platform.ts

Synchronize server and client system bundle lists for IsSystemBundle checks.

fix: add missing system bundle names to client code

---

apps/platform-integration-tests/bundle/routes/redirect_test.yaml
apps/platform-integration-tests/hurl_specs/redirect_route_type.hurl
apps/platform/pkg/controller/route.go

Ensures route params are available for server side redirected routes.
Updated test case to include coverage for route params.

fix: server side redirect routes should merge route params

---

apps/platform-integration-tests/hurl_specs/listener_bot_http_post_api.hurl
apps/platform/pkg/bot/jsdialect/bothttpapi_test.go
apps/platform/pkg/controller/filejson/respondjson.go
apps/platform/pkg/middleware/gzip.go

Uses `application/json` instead of `text/json` for content type when responding with JSON.

chore: use application/json instead of text/json content type

---

apps/cli/pkg/auth/login.go

Eliminates profile check during login in legacy CLI login methods (platform & mock).
This unifies behavior between all supported CLI login process (browser, platform, mock).  In short, either the user logs in successfully or doesn't but its irrespective of their "permissions" to perform certain actions.  If they are unable to perform a CLI command, they will receive the corresponding permission failure messages at that time.
Manually tested and confirmed.

chore: eliminate profile check for legacy cli login methods

---

apps/cli/pkg/auth/login.go
apps/cli/pkg/auth/loginresponse.go
apps/platform/pkg/preload/mergetypes.go

Eliminates the "custom" CLI types for login response since the full type was being sent to CLI anyway. See comments for details and TODOs.
In short, this eliminates the maintenance overhead which introduces uncessary risk when changes are made and provided nearly no benefit since the data was coming across the wire anyway.

chore: refactor login response types in CLI

---

apps/cli/pkg/auth/login.go
apps/cli/pkg/auth/logout.go
apps/cli/pkg/call/call.go
apps/cli/pkg/cmd/generate.go
apps/cli/pkg/command/app/clone.go
apps/cli/pkg/command/app/delete.go
apps/cli/pkg/command/bundle/create.go
apps/cli/pkg/command/generate.go
apps/cli/pkg/command/upsert.go
apps/cli/pkg/command/workspace/retrieve.go
apps/cli/pkg/command/workspace/truncate.go
apps/cli/pkg/config/session.go
apps/cli/pkg/wire/save.go
apps/platform/pkg/auth/login.go
apps/platform/pkg/bot/jsdialect/sessionapi.go
apps/platform/pkg/preload/mergetypes.go
apps/platform/pkg/sess/session.go

Standardize naming of `sessionID` in go (eliminate mix use of `sessionId` & `sessionID`).

chore: consistent use of sessionID in go code

---

apps/cli/go.mod
apps/platform/Dockerfile
apps/platform/go.mod
go.work

chore: upgrade go 1.24.5

---

apps/platform/pkg/middleware/authenticate.go

Eliminates "redirect to login logic" in authentication middleware in the two places that it existed.
This PR is the next of several PRs focused on addressing some underlying issues with middleware, authentication and session management.  This PR is the most substantial of the changes being made and is focused on one of the core underlying issues with the way middleware was working previously.
In short, redirecting to login in middleware is prone to several different issues:
1. We don't know if the route being requested is public or protected as that's the responsibility of the controller - the middlware should simply be establishing a valid session for the request
2. We don't know if the site even has a login page - while we could determine this in middleware, issue 1 still applies
The …

fix: eliminate auth middleware redirect to login logic

---

apps/platform/pkg/auth/session.go
apps/platform/pkg/auth/site.go
apps/platform/pkg/middleware/authenticate.go

Ensures that everywhere we "create" a Uesio session, regardless of whether its for a browser based session or a "system" type of session, the session has an ID.
Previously, these types of sessions would not have an ID (it would be empty string) so anything downstream which may be expecting an ID wouldn't have one.  This could lead to several issues including limited traceability, output, etc.
NOTE: This does not address the underlying concern that a "sess.Session" (aka. a Uesio session) and a session.Session (aka. a Browser session) are both considers a "Session" currently in the code but it could be one or the other type of session and a uesio session may or may not have a browser session backing it.  The code should be refactored in to more clear typings so that its esaier to discern, …

chore: all "uesio" sessions should have an id

---

apps/cli/go.mod
apps/cli/go.sum
apps/platform/pkg/auth/login.go
apps/platform/pkg/auth/responses.go
apps/platform/pkg/auth/samlauth/samlauth.go
apps/platform/pkg/controller/logout.go
apps/platform/pkg/controller/signup.go
apps/platform/pkg/routing/routing.go
libs/ui/src/bands/user/operations.ts
libs/ui/src/platform/platform.ts

Modifies "login responses" to always contain a `redirectPath` eliminating the `routeNamespace/routeName` usage.
The reason for this change is a few-fold:
1. We always hit the server to process a "login related' event but then, unless an `r=<path>` was specified, would send the route namespace/name to the client who would then go back to the server to get the path and then `pushState`.  This 2nd call to get information we could already obtain impacts performance unnecessarily.
2. While we are processing the "login related event", we are changing the session (auth) token so any inflight requests from the browser may fail depending on when they get processed through middleware.  There is actually another bug (PR coming) where we don't "remove" the "old session" but assuming we were doing …

fix: always generate redirectpath on login events server-side

---

apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/cli_token.go
apps/platform/pkg/auth/login.go
apps/platform/pkg/auth/redis-session-store.go
apps/platform/pkg/auth/session.go
apps/platform/pkg/controller/logout.go
apps/platform/pkg/controller/signup.go
apps/platform/pkg/middleware/authenticate.go
apps/platform/pkg/sess/session.go

No functional changes of any kind.  Just refactoring the location of some of the auth related code as the next step (many more yet to come) of improving auth flows.  Focused on putting code in packages and files were it more appropriately fits than its prior location.
Major win here is decoupling sess package from its dependencies on icza and eliminating it from having "controller" functions. Also, eliminating some middleware only functions from auth package.

chore: refactor location of auth related code

---

apps/cli/pkg/auth/login.go
apps/cli/pkg/auth/logout.go
apps/cli/pkg/auth/server.go
apps/cli/pkg/command/logout.go

In #5033, a "profile" check was removed from the start of login flow and instead, if we had a current user, we just no-op'd the login. However, this created an issue whereby if there is a `token` in config but that token is no longer valid (e.g., it expired), the auth check API returns a "Guest" user. The change in logic meant that we would always get a user back (barring any unforseen failure) and never proceed with login.  The only way to login was to ensure that the local config did not have a 'token' value.
This PR resolves that issue by eliminating the "check" completely.  It's really unnecessary as the user is asking us to login so we should do as they ask - this is the way the majority of CLI login processes work. The alternative is to ask them to logout first if we have an …

fix: cli auth check during login

---

apps/platform/pkg/auth/session.go

Cookie SameSite setting should use the default of Lax. Forgot to remove testing code.
Manually confirmed Lax is set for the cookie. ci & e2e will cover rest.

chore: samesite should use the default of Lax

---

apps/platform-integration-tests/hurl_specs/redirect_to_login_if_workspace_session_invalid.hurl
apps/platform/pkg/auth/session.go
apps/platform/pkg/middleware/authenticate.go

Eliminates creating a browser session for public users.
Previously, we would create a browser session for public users which included storing the siteid along with the public userid in the session cache. However, there are several downsides to this:
1) Every request must go to the cache to get the public user information
2) Every request must retrieve the user from the user cache
This happens on every request (page, js, css, font, etc.) and has no value because all we are doing is storing the information that we know anyway via `GetPublicUser`.
By eliminating creating a browser session for public user, we avoid all the unnecessary session cache operations which will improve performance of the site for public users as well as reduce utilization/cost of the session store (e.g., redis). …

chore: do not create browser sessions for public user

---

apps/cli/pkg/auth/login.go
apps/cli/pkg/call/call.go
apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/google/googleauth.go
apps/platform/pkg/auth/mock/mockauth.go
apps/platform/pkg/auth/platform/platform.go
apps/platform/pkg/auth/responses.go
apps/platform/pkg/auth/samlauth/samlauth.go
apps/platform/pkg/cmd/serve.go
apps/platform/pkg/controller/login.go

With the recent refactoring of auth flows, there is an opportunity to improve the CLI login for `mock/platform` logins to target the CLI specifically as the client.  Previously, these flows called the same endpoints as the web based login flows and therefore received responses as if they were a web client - but the CLI is not a web client :)  The refactoring provides the opportunity to orchestrate a different flow for the CLI.  One example of why this was needed is because the web based login returns an HTTP 200 with `redirectPath` when a users account requires a password reset.  The CLI doesn't expect a redirectPath and since the status was 200, didn't know what to do since there was no token returned.
This PR does three things:
1. Adds new a new `auth/cli/<provider>/login` route for CLI …

chore: improve cli login

---

apps/cli/go.mod
apps/cli/go.sum
apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/samlauth/samlauth.go
apps/platform/pkg/auth/session.go
apps/platform/pkg/auth/site.go
apps/platform/pkg/bundle/bundles.go
apps/platform/pkg/bundlestore/platformbundlestore/platformbundlestore.go
apps/platform/pkg/bundlestore/workspacebundlestore/workspacebundlecacheutils.go
apps/platform/pkg/cmd/migrate.go
apps/platform/pkg/cmd/seed.go
apps/platform/pkg/controller/ctlutil/errors.go
apps/platform/pkg/controller/server.go
apps/platform/pkg/datasource/domain.go
apps/platform/pkg/datasource/licensing.go
apps/platform/pkg/invoices/invoices.go
apps/platform/pkg/usage/usage_worker/usage_worker.go

What this does: Adds a traceid for log correlation to places where we use a background context.
What this does NOT do: 
1. Fix the underlying issues with use of background context - in most places that we currently use one, we should not be and instead using session.Context()/request.Context()
2. Ensure that slog statements are using the *Context variants so that the traceid will actually appear in the logs
More PRs coming on improving the flow and use of contexts, this is just the next step.

chore: add traceid to background contexts

---

apps/platform-integration-tests/hurl_specs/bedrock_integration_actions.hurl
apps/platform/pkg/integ/bedrock/bedrock.go
apps/platform/pkg/integ/bedrock/claude.go
libs/apps/uesio/aikit/bundle/fields/uesio/aikit/thread/agent.yaml

This PR returns the previous functionality of allowing the `uesio/aikit.bedrock` `invokemodel` action to accept an `input` param and a `system` param that are strings.
All ai functionality in uesio should continue to work the same. The CRM app ai tab on the lead detail page should work now as well.

fix: allow system and input params for invokemodel

---

apps/platform/pkg/auth/auth.go
apps/platform/pkg/auth/google/googleauth.go
apps/platform/pkg/auth/platform/platform.go
apps/platform/pkg/auth/samlauth/samlauth.go
apps/platform/pkg/controller/bundlesretrieve.go
apps/platform/pkg/controller/ctlutil/errors.go
apps/platform/pkg/controller/retrieve.go

Replace use of `context.Background` with the `current context` when its available.  The only things really remaining that use `context.Background` are:
1. Singletons
2. Tests
3. Scheduled jobs

chore: use current context instead of context.Background

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/field/file.tsx

Ensures that the record for a "file" field is correctly updated when the file is changed (deleted or changed).
Previously, the record value was updated but the change wasn't fully tracked resulting in "changes" being empty.
Historically, "files" used to use wire functionality, however when the change was made for them to use wire functionality, this code wasn't updated to update the wire.
Tested manually and confirmed that the wire is updated as expected and changes reflect the corresponding change that was made.
ci & e2e will cover rest.

fix: ensure record is updated when file changes in file field

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/fileimage/fileimage.tsx
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/filevideo/filevideo.tsx

Fixes a regression introduced in #5100 that resulted in unnecessary FileImage & FileVideo component re-renders.
Manually confirmed no unnecessary re-renders.

chore: avoid file image & video component re-renders

---

apps/cli/pkg/auth/login.go
apps/cli/pkg/command/login.go

Fixes a regression that resulted in every command requiring the user to go through the login process in order to complete the command.
In prior PRs, #5033 & #5072, work was done to improve login and part of that was to eliminate the "auth check" as it really should be unnecessary.  However, it actually is necessary, at least for now, for a few reasons:
1. All commands go through `auth.Login` including the `Login` command itself. With the `Check` removed, every command was going through the entire login process even if there was a token present.
2. `Check` will always return a user (barring any unforeseen failure), although the user may be the `Guest`. If the user returned is `Guest`, there is no user logged in so we need to process a login cycle.
3. Due to the fact that we return "errors" …

fix: cli login

---

libs/ui/src/hooks/fileapi.ts

Fixes two issues with `useUserFile`:
1. If `uesio/core.data` existed, but its value was "empty string", the fetch would occur
2. Did not update `content` when `uesio/core.data` changed - The intended use of the hook is to provide the "current content", not just the original content since it is used in `FileText` component which passes it to monaco as an intended controlled input.  This created a bug where if you typed something in the editor, then hit the `Cancel` button, the wire data would change, however the hook would still return the original value which was passed to Monaco which detected that `value` hasn't changed so it should maintain it's internal buffer state resulting in the text that was typed staying visible in the editor.  Underneath, the wire was correct but the editor did …

fix: ensure `useUserFile` correctly detects and honors `uesio/core.data` value

---

libs/apps/uesio/studio/bundle/views/agent.yaml
libs/apps/uesio/studio/bundle/views/bot.yaml

Migrates `bot` and `agent` views to the standardized structure/layout.
Resolves the following issues:
1. Consistent UI/UX relative to other "detail" type views
2. When navigating the view, the record was in "READ" mode but the monaco editor was in "EDIT" mode
3. After saving changes, the Monaco editor remained in "EDIT" mode
Manually tested and confirmed expected behavior.

chore: migrates bot & agent views to standardized structure

---

libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/codefield/codefield.tsx

With the changes made in #5111 & specifically #5112, it exposed an issue in the way we respond to `onChange` events from Monaco.  Those two PRs ensured that we are using Monaco with a controlled input and also ensured that we toggle the `mode` from READ->EDIT and vice-versa based on user actions.
The proper toggling of the mode resulted in Monaco firing the `onChange` event when changing back to READ mode even though the controlled input is responsible for the change.  Monaco is smart about not firing onChange when in EDIT mode but not when in READ mode.
This PR works around the Monaco issue by detecting the current mode and old/new value and only calling `setValue` when in EDIT mode and the value is actually different than what we have in state (meaning the user typed something in the …

fix: ensure setValue only called when legitimate change is occuring

---

apps/platform/pkg/auth/cache.go

Fixes the params passed to `getHostKey` to ensure the cache key is built correctly.
Regression from #5110.
Manual testing to ensure cache key is deleted as expected.

fix: build host key correctly

---

apps/platform/pkg/bot/systemdialect/systembot_before_sitedomain.go

Enforces single label subdomains for sites.
Wildcard certs typically restrict to single label subdomains (e.g., *.example.com) and most cert providers will not issue multi-label wildcard certs. If a multi-label subdomain is required, an explicit certificate, either for the subdomain explicitly or a wildcard for the top-most level of the subdomain, must be used which requires infrastructure configuration depending on the hosting environment.
Tested manually and confirmed single label subdomains are enforced.

fix: enforce single label subdomain

---

libs/apps/uesio/studio/bundle/views/domains.yaml

When user does not have "Manage Domains" feature flag, they can only create subdomains.
Adjusts the labels to align with feature flag detection, explicitly using `subdomain` terminology instead of `domain` terminology if the user does not have the feature flag enabled.
Manually tested and confirmed.

chore: improve labels on domains view based on feature flag setting

---

apps/platform/pkg/bot/systemdialect/systembot_after_userfile.go
libs/apps/uesio/appkit/bundle/components/section_attachments.yaml
libs/apps/uesio/appkit/bundle/views/file_attachments.yaml
libs/apps/uesio/io/bundle/componentpacks/main/src/utilities/userfile/userfile.tsx

Fixes an issue where on 2nd (and subsequent) uploads of a userfile to and attachment, the `collection` would be `userfile` instead of the `id` of the collection that "owns" the userfile.  Additionally, adds server side validation to ensure that a userfile can never have a collection of `userfile` and adds toast notifications to `uploadFile` and `deleteFile` to surface errors to user in UI.
In [this commit](https://github.com/ues-io/uesio/commit/ade91a8913cd23735d86da29cd3270d70a35efc7#diff-55d7c9ea51b4f7299ecf6ba9cb00a07c2970652389e1e79b334a5eb303cb2f5dL24), the `collectionid` value was changed to use the `$Collection{id}`, however when there is a record in context for `userfile`, the collection is now `userfile`.
@humandad  - The hierarchy and flow of these components is a little odd in …

fix: ensure collectionId of user file matches collection of recordid
